project_name: ff
source:
  type: fabric
  identity_id: b42b84ee-4f0e-484e-9889-54d2c7298ff9
  workspace_id: d6e5bfe7-c544-4474-ac3b-ddce9a02e712
  workspace: semabridge
  models:
  - Competitive Marketing Analysis
targets:
- type: snowflake
ui:
  intermediate_format: osi
  editor_mode: form
  output_format: osi
options:
  auto_relationships: true
  generate_descriptions: true
  write_strategy: copy
project_id: proj-ff
display_name: ff
owner_user_id: '1'
project_metadata:
  owner_user_id: '1'
target:
  type: snowflake
