project_name: fd
source:
  type: fabric
  identity_id: d3590a59-bb80-4947-a0d4-f5750145c8cb
  workspace_id: d6e5bfe7-c544-4474-ac3b-ddce9a02e712
  workspace: semabridge
  models:
  - continent
targets:
- type: databricks
ui:
  intermediate_format: osi
  editor_mode: form
selection:
  model_ids:
  - 9fc7b015-c010-4fc5-b029-982bf1f64401
options:
  auto_relationships: true
  generate_descriptions: true
project_id: proj-fd
display_name: fd
owner_user_id: '3'
project_metadata:
  owner_user_id: '3'
