project_name: multi_Sf
source:
  type: fabric
  identity_id: 5e5e9d82-3030-459c-bbc4-0903098a568a
  workspace_id: d875c0c3-59e9-4d55-a7f0-99595b756718
  workspace: semabridge
  models:
  - Corporate Spend
  - Employee Hiring and History
  - Regional Sales Sample
  - Competitive Marketing Analysis orig
  - Client Data
  - P2P_NEW_ Spend_Semantic_Model
targets:
- type: snowflake
  identity_id: 241347f2-70b3-4bb5-9586-85bc50b2bd7b
mappings:
- source: Corporate Spend
  target: CORPORATE_SPEND
  type: table
  columns:
  - source: id
    target: ID
    type: integer
    primary_key: true
  - source: name
    target: NAME
    type: string
  - source: created_at
    target: CREATED_AT
    type: timestamp
  - source: updated_at
    target: UPDATED_AT
    type: timestamp
- source: Employee Hiring and History
  target: EMPLOYEE_HIRING_AND_HISTORY
  type: table
  columns:
  - source: id
    target: ID
    type: integer
    primary_key: true
  - source: name
    target: NAME
    type: string
  - source: created_at
    target: CREATED_AT
    type: timestamp
  - source: updated_at
    target: UPDATED_AT
    type: timestamp
- source: Regional Sales Sample
  target: REGIONAL_SALES_SAMPLE
  type: table
  columns:
  - source: id
    target: ID
    type: integer
    primary_key: true
  - source: name
    target: NAME
    type: string
  - source: created_at
    target: CREATED_AT
    type: timestamp
  - source: updated_at
    target: UPDATED_AT
    type: timestamp
- source: Competitive Marketing Analysis orig
  target: COMPETITIVE_MARKETING_ANALYSIS_ORIG
  type: table
  columns:
  - source: id
    target: ID
    type: integer
    primary_key: true
  - source: name
    target: NAME
    type: string
  - source: created_at
    target: CREATED_AT
    type: timestamp
  - source: updated_at
    target: UPDATED_AT
    type: timestamp
- source: Client Data
  target: CLIENT_DATA
  type: table
  columns:
  - source: id
    target: ID
    type: integer
    primary_key: true
  - source: name
    target: NAME
    type: string
  - source: created_at
    target: CREATED_AT
    type: timestamp
  - source: updated_at
    target: UPDATED_AT
    type: timestamp
- source: P2P_NEW_ Spend_Semantic_Model
  target: P2P_NEW_SPEND_SEMANTIC_MODEL
  type: table
  columns:
  - source: id
    target: ID
    type: integer
    primary_key: true
  - source: name
    target: NAME
    type: string
  - source: created_at
    target: CREATED_AT
    type: timestamp
  - source: updated_at
    target: UPDATED_AT
    type: timestamp
ui:
  intermediate_format: osi
  editor_mode: form
selection:
  model_ids:
  - cfbd1669-4cbe-4dbb-a291-ff3bcd6b1053
  - 0380514b-a532-4a82-9066-09de85a65d19
  - 89589d2b-3549-40b9-8879-76360c3a3dae
  - 6aa0a303-dc1f-4457-86b3-90888e995c0f
  - 0794fdcc-d85f-4d93-a42c-8bacaad04819
  - 783f4b2a-a279-4b8f-87b6-1264f28396e6
options:
  auto_relationships: true
  generate_descriptions: true
project_id: proj-multi_sf
display_name: multi_Sf
