project_name: DATTATATATA
source:
  type: fabric
  identity_id: c505f63e-bb85-439a-be22-d7bcbde8a8cc
  workspace_id: d875c0c3-59e9-4d55-a7f0-99595b756718
  workspace: semabridge
  models:
  - Core_Finance_v1
  - Inventory Semantic Model
targets:
- type: snowflake
  identity_id: 5567550b-8628-43cc-8f0c-c69f74ae7b31
mappings:
- source: Core_Finance_v1
  target: CORE_FINANCE_V1
  type: table
  columns:
  - source: id
    target: ID
    type: integer
    primary_key: true
  - source: name
    target: NAME
    type: string
  - source: created_at
    target: CREATED_AT
    type: timestamp
  - source: updated_at
    target: UPDATED_AT
    type: timestamp
- source: Inventory Semantic Model
  target: INVENTORY_SEMANTIC_MODEL
  type: table
  columns:
  - source: id
    target: ID
    type: integer
    primary_key: true
  - source: name
    target: NAME
    type: string
  - source: created_at
    target: CREATED_AT
    type: timestamp
  - source: updated_at
    target: UPDATED_AT
    type: timestamp
ui:
  intermediate_format: osi
  editor_mode: form
  output_format: osi
selection:
  model_ids:
  - bbe97d8c-bf99-457f-b322-6c5e7a948171
  - 6c73961a-00c4-4610-b035-232a434e5d50
options:
  auto_relationships: true
  generate_descriptions: true
target:
  type: snowflake
mappings_overrides:
- source_path: datasets.Core_Finance_v1
  target_name: CORE_FINANCE_V1
  entity_kind: table
  source_name: Core_Finance_v1
- source_path: datasets.Core_Finance_v1.columns.id
  target_name: ID
  entity_kind: column
  source_name: id
- source_path: datasets.Core_Finance_v1.columns.name
  target_name: NAME
  entity_kind: column
  source_name: name
project_id: proj-1777450048984
display_name: DATTATATATA
