project_name: cdata
source:
  type: fabric
  identity_id: c505f63e-bb85-439a-be22-d7bcbde8a8cc
  workspace_id: d875c0c3-59e9-4d55-a7f0-99595b756718
  workspace: semabridge
  models:
  - Client Data
  - CLIENT_DATA_SEMANTIC
targets:
- type: snowflake
mappings:
- source: Client Data
  target: CLIENT_DATA
  type: table
  columns:
  - source: id
    target: ID
    type: integer
    primary_key: true
  - source: name
    target: NAME
    type: string
  - source: created_at
    target: CREATED_AT
    type: timestamp
  - source: updated_at
    target: UPDATED_AT
    type: timestamp
- source: CLIENT_DATA_SEMANTIC
  target: CLIENT_DATA_SEMANTIC
  type: table
  columns:
  - source: id
    target: ID
    type: integer
    primary_key: true
  - source: name
    target: NAME
    type: string
  - source: created_at
    target: CREATED_AT
    type: timestamp
  - source: updated_at
    target: UPDATED_AT
    type: timestamp
ui:
  intermediate_format: osi
  editor_mode: form
  output_format: osi
selection:
  model_ids:
  - 0794fdcc-d85f-4d93-a42c-8bacaad04819
  - d68b7670-5f6c-47ac-8c2a-32f5885a3e75
options:
  auto_relationships: true
  generate_descriptions: true
target:
  type: snowflake
mappings_overrides:
- source_path: datasets.Client Data
  target_name: CLIENT_DATA
  entity_kind: table
  source_name: Client Data
- source_path: datasets.Client Data.columns.id
  target_name: ID
  entity_kind: column
  source_name: id
- source_path: datasets.Client Data.columns.name
  target_name: NAME
  entity_kind: column
  source_name: name
project_id: proj-1777039731657
display_name: cdata
