project_name: ff
source:
  type: fabric
  identity_id: 5e5e9d82-3030-459c-bbc4-0903098a568a
  workspace_id: d875c0c3-59e9-4d55-a7f0-99595b756718
  workspace: semabridge
  models:
  - continent
targets:
- type: snowflake
  identity_id: 241347f2-70b3-4bb5-9586-85bc50b2bd7b
mappings:
- source: continent
  target: CONTINENT
  type: table
  columns:
  - source: id
    target: ID
    type: integer
    primary_key: true
  - source: name
    target: NAME
    type: string
  - source: created_at
    target: CREATED_AT
    type: timestamp
  - source: updated_at
    target: UPDATED_AT
    type: timestamp
ui:
  intermediate_format: osi
  editor_mode: form
  output_format: osi
selection:
  model_ids:
  - d32e8900-31cc-4647-872d-08a7e62bf03b
options:
  auto_relationships: true
  generate_descriptions: true
project_id: proj-ff
display_name: ff
target:
  type: snowflake
owner_user_id: '3'
project_metadata:
  owner_user_id: '3'
