project_name: fd
source:
  type: fabric
  identity_id: b5cb6609-0ef4-4a1c-9d46-e415f8ca9c91
  workspace_id: d6e5bfe7-c544-4474-ac3b-ddce9a02e712
  workspace: semabridge
  models:
  - continent
targets:
- type: databricks
  identity_id: 157f7249-c882-44e0-b0f9-36be29525c3c
mappings:
- source: continent
  target: CONTINENT
  type: table
  columns:
  - source: id
    target: ID
    type: integer
    primary_key: true
  - source: name
    target: NAME
    type: string
  - source: created_at
    target: CREATED_AT
    type: timestamp
  - source: updated_at
    target: UPDATED_AT
    type: timestamp
ui:
  intermediate_format: osi
  editor_mode: form
  output_format: osi
selection:
  model_ids:
  - d32e8900-31cc-4647-872d-08a7e62bf03b
options:
  auto_relationships: true
  generate_descriptions: true
project_id: proj-fd
display_name: fd
target:
  type: databricks
