"""Patch tmsl_to_osi.py: normalize column names before passing to RelationshipDetector."""
p = "src/semabridge/converter/tmsl_to_osi.py"
content = open(p, "rb").read().decode("utf-8")

old = (
    "            if osi_model.datasets:\r\n"
    "                try:\r\n"
    "                    from semabridge.connectors.relationship_detector import RelationshipDetector\r\n"
    "\r\n"
    "                    tables_meta: Dict[str, Dict[str, Any]] = {\r\n"
    "                        ds.unique_name: {\"row_count\": 0} for ds in osi_model.datasets\r\n"
    "                    }\r\n"
    "                    columns_meta: Dict[str, List[Dict[str, Any]]] = {\r\n"
    "                        ds.unique_name: [\r\n"
    "                            {\r\n"
    "                                \"name\": c.unique_name,\r\n"
    "                                \"data_type\": (\r\n"
    "                                    c.data_type.value if hasattr(c.data_type, \"value\") else str(c.data_type)\r\n"
    "                                ),\r\n"
    "                            }\r\n"
    "                            for c in ds.columns\r\n"
    "                        ]\r\n"
    "                        for ds in osi_model.datasets\r\n"
    "                    }\r\n"
    "                    pks_meta: Dict[str, List[str]] = {\r\n"
    "                        ds.unique_name: [c.unique_name for c in ds.columns if c.is_key]\r\n"
    "                        for ds in osi_model.datasets\r\n"
    "                    }\r\n"
    "\r\n"
    "                    detector = RelationshipDetector(tables_meta, columns_meta, pks_meta)\r\n"
    "                    inferred_rels = detector.detect_all()\r\n"
    "                    if inferred_rels:\r\n"
    "                        seen_signatures = {\r\n"
    "                            (\r\n"
    "                                r.from_dataset.casefold(),\r\n"
    "                                (r.from_columns[0] if r.from_columns else \"\").casefold(),\r\n"
    "                                r.to_dataset.casefold(),\r\n"
    "                                (r.to_columns[0] if r.to_columns else \"\").casefold(),\r\n"
    "                            )\r\n"
    "                            for r in osi_model.relationships\r\n"
    "                        }\r\n"
    "                        added = 0\r\n"
    "                        for rel in inferred_rels:\r\n"
    "                            sig = (\r\n"
    "                                str(rel.get(\"from_table\", \"\")).casefold(),\r\n"
    "                                str(rel.get(\"from_column\", \"\")).casefold(),\r\n"
    "                                str(rel.get(\"to_table\", \"\")).casefold(),\r\n"
    "                                str(rel.get(\"to_column\", \"\")).casefold(),\r\n"
    "                            )\r\n"
    "                            if sig in seen_signatures:\r\n"
    "                                continue\r\n"
    "                            from_ds = valid_dataset_map.get(str(rel.get(\"from_table\", \"\")).casefold())\r\n"
    "                            to_ds = valid_dataset_map.get(str(rel.get(\"to_table\", \"\")).casefold())\r\n"
    "                            from_col = str(rel.get(\"from_column\", \"\")).strip()\r\n"
    "                            to_col = str(rel.get(\"to_column\", \"\")).strip()\r\n"
    "                            if not (from_ds and to_ds and from_col and to_col):\r\n"
    "                                continue\r\n"
    "                            osi_model.relationships.append(\r\n"
    "                                OSIRelationship(\r\n"
    "                                    unique_name=generate_relationship_name(from_ds, from_col, to_ds, to_col),\r\n"
    "                                    from_dataset=from_ds,\r\n"
    "                                    from_columns=[from_col],\r\n"
    "                                    to_dataset=to_ds,\r\n"
    "                                    to_columns=[to_col],\r\n"
    "                                    cardinality=OSICardinality.MANY_TO_ONE,\r\n"
    "                                    cross_filter_direction=OSICrossFilterDirection.SINGLE,\r\n"
    "                                    is_active=True,\r\n"
    "                                )\r\n"
    "                            )\r\n"
    "                            seen_signatures.add(sig)\r\n"
    "                            added += 1\r\n"
    "                        if added:\r\n"
    "                            logger.info(\r\n"
    "                                \"Supplemented %d inferred relationship(s) (total: %d)\",\r\n"
    "                                added,\r\n"
    "                                len(osi_model.relationships),\r\n"
    "                            )\r\n"
    "                except Exception as exc:\r\n"
    "                    logger.warning(\"Relationship inference supplement failed: %s\", exc)"
)

new = (
    "            if osi_model.datasets:\r\n"
    "                try:\r\n"
    "                    from semabridge.connectors.relationship_detector import RelationshipDetector\r\n"
    "\r\n"
    "                    # Normalize Fabric column names (spaces -> underscores) before\r\n"
    "                    # passing to RelationshipDetector, which uses FK-suffix patterns\r\n"
    "                    # that require underscore-separated names (e.g. BU_KEY not 'BU Key').\r\n"
    "                    # Build reverse maps to recover original names from normalized ones.\r\n"
    "                    def _norm(name: str) -> str:\r\n"
    "                        return name.replace(\" \", \"_\")\r\n"
    "\r\n"
    "                    # col_orig_map[ds_name][norm_col] = original_col\r\n"
    "                    col_orig_map: Dict[str, Dict[str, str]] = {}\r\n"
    "                    for ds in osi_model.datasets:\r\n"
    "                        col_orig_map[ds.unique_name] = {_norm(c.unique_name): c.unique_name for c in ds.columns}\r\n"
    "\r\n"
    "                    tables_meta: Dict[str, Dict[str, Any]] = {\r\n"
    "                        ds.unique_name: {\"row_count\": 0} for ds in osi_model.datasets\r\n"
    "                    }\r\n"
    "                    columns_meta: Dict[str, List[Dict[str, Any]]] = {\r\n"
    "                        ds.unique_name: [\r\n"
    "                            {\r\n"
    "                                \"name\": _norm(c.unique_name),\r\n"
    "                                \"data_type\": (\r\n"
    "                                    c.data_type.value if hasattr(c.data_type, \"value\") else str(c.data_type)\r\n"
    "                                ),\r\n"
    "                            }\r\n"
    "                            for c in ds.columns\r\n"
    "                        ]\r\n"
    "                        for ds in osi_model.datasets\r\n"
    "                    }\r\n"
    "                    # Use normalized PK names; also add YearPeriod-style join cols\r\n"
    "                    # as PKs when they appear in exactly one other table.\r\n"
    "                    pks_meta: Dict[str, List[str]] = {\r\n"
    "                        ds.unique_name: [_norm(c.unique_name) for c in ds.columns if c.is_key]\r\n"
    "                        for ds in osi_model.datasets\r\n"
    "                    }\r\n"
    "                    # Extend pks_meta: treat a normalized column as a \"virtual PK\"\r\n"
    "                    # of table T if it is the *only* table (other than Fact) that has\r\n"
    "                    # that column -- a reliable signal for YearPeriod -> Calendar joins.\r\n"
    "                    norm_col_to_tables: Dict[str, list] = {}\r\n"
    "                    for ds in osi_model.datasets:\r\n"
    "                        for c in ds.columns:\r\n"
    "                            nc = _norm(c.unique_name)\r\n"
    "                            norm_col_to_tables.setdefault(nc, []).append(ds.unique_name)\r\n"
    "                    for nc, ds_list in norm_col_to_tables.items():\r\n"
    "                        if len(ds_list) == 2:\r\n"
    "                            for ds_name in ds_list:\r\n"
    "                                if nc not in pks_meta.get(ds_name, []):\r\n"
    "                                    pks_meta.setdefault(ds_name, []).append(nc)\r\n"
    "\r\n"
    "                    detector = RelationshipDetector(tables_meta, columns_meta, pks_meta)\r\n"
    "                    inferred_rels = detector.detect_all()\r\n"
    "                    if inferred_rels:\r\n"
    "                        # Existing rels use original (possibly space-containing) names.\r\n"
    "                        seen_signatures = {\r\n"
    "                            (\r\n"
    "                                r.from_dataset.casefold(),\r\n"
    "                                _norm(r.from_columns[0] if r.from_columns else \"\").casefold(),\r\n"
    "                                r.to_dataset.casefold(),\r\n"
    "                                _norm(r.to_columns[0] if r.to_columns else \"\").casefold(),\r\n"
    "                            )\r\n"
    "                            for r in osi_model.relationships\r\n"
    "                        }\r\n"
    "                        added = 0\r\n"
    "                        for rel in inferred_rels:\r\n"
    "                            from_table = str(rel.get(\"from_table\", \"\"))\r\n"
    "                            to_table = str(rel.get(\"to_table\", \"\"))\r\n"
    "                            from_col_norm = str(rel.get(\"from_column\", \"\")).strip()\r\n"
    "                            to_col_norm = str(rel.get(\"to_column\", \"\")).strip()\r\n"
    "                            sig = (\r\n"
    "                                from_table.casefold(),\r\n"
    "                                from_col_norm.casefold(),\r\n"
    "                                to_table.casefold(),\r\n"
    "                                to_col_norm.casefold(),\r\n"
    "                            )\r\n"
    "                            if sig in seen_signatures:\r\n"
    "                                continue\r\n"
    "                            from_ds = valid_dataset_map.get(from_table.casefold())\r\n"
    "                            to_ds = valid_dataset_map.get(to_table.casefold())\r\n"
    "                            # Recover original (space-containing) column names\r\n"
    "                            from_col = col_orig_map.get(from_ds or \"\", {}).get(from_col_norm, from_col_norm)\r\n"
    "                            to_col = col_orig_map.get(to_ds or \"\", {}).get(to_col_norm, to_col_norm)\r\n"
    "                            if not (from_ds and to_ds and from_col and to_col):\r\n"
    "                                continue\r\n"
    "                            osi_model.relationships.append(\r\n"
    "                                OSIRelationship(\r\n"
    "                                    unique_name=generate_relationship_name(from_ds, from_col, to_ds, to_col),\r\n"
    "                                    from_dataset=from_ds,\r\n"
    "                                    from_columns=[from_col],\r\n"
    "                                    to_dataset=to_ds,\r\n"
    "                                    to_columns=[to_col],\r\n"
    "                                    cardinality=OSICardinality.MANY_TO_ONE,\r\n"
    "                                    cross_filter_direction=OSICrossFilterDirection.SINGLE,\r\n"
    "                                    is_active=True,\r\n"
    "                                )\r\n"
    "                            )\r\n"
    "                            seen_signatures.add(sig)\r\n"
    "                            added += 1\r\n"
    "                        if added:\r\n"
    "                            logger.info(\r\n"
    "                                \"Supplemented %d inferred relationship(s) (total: %d)\",\r\n"
    "                                added,\r\n"
    "                                len(osi_model.relationships),\r\n"
    "                            )\r\n"
    "                except Exception as exc:\r\n"
    "                    logger.warning(\"Relationship inference supplement failed: %s\", exc)"
)

if old in content:
    content = content.replace(old, new, 1)
    open(p, "wb").write(content.encode("utf-8"))
    print("DONE - supplement block updated with name normalization")
else:
    print("NOT FOUND")
    idx = content.find("if osi_model.datasets:")
    print(f"  'if osi_model.datasets:' found at: {[m for m in range(len(content)) if content[m:m+22] == 'if osi_model.datasets:'][:5]}")
