create or replace semantic view PROJPBIXTEST_SEMANTIC
	tables (
		SEMABRIDGE.SEMABRIDGE_WORKSPACE.CATEGORY primary key (CATEGORY),
		COL_DATE as SEMABRIDGE.SEMABRIDGE_WORKSPACE.DATE primary key (COL_DATE),
		SEMABRIDGE.SEMABRIDGE_WORKSPACE.GEO primary key (ZIP),
		SEMABRIDGE.SEMABRIDGE_WORKSPACE.INDICATORS primary key (SORT),
		KPI as (
			SELECT
        f.*,
        NULL AS "_CURRENT_FISCAL_PERIOD"
    FROM "SEMABRIDGE"."SEMABRIDGE_WORKSPACE"."KPI_ENRICHED" f
		) primary key (CATEGORY),
		MANUFACTURER as (
			SELECT
        f.*,
        NULL AS "_CURRENT_FISCAL_PERIOD"
    FROM "SEMABRIDGE"."SEMABRIDGE_WORKSPACE"."MANUFACTURER" f
		) primary key (MANUFACTURERID),
		SEMABRIDGE.SEMABRIDGE_WORKSPACE.PRODUCT primary key (PRODUCTID),
		SALESFACT as (
			SELECT
        f.*,
        NULL AS "_CURRENT_FISCAL_PERIOD"
    FROM "SEMABRIDGE"."SEMABRIDGE_WORKSPACE"."SALESFACT_ENRICHED" f
		) primary key (PRODUCTID),
		SEMABRIDGE.SEMABRIDGE_WORKSPACE.SENTIMENT primary key (DATEID)
	)
	relationships (
		PRODUCT_SEGMENT_CATEGORY_CATEGORY as PRODUCT(SEGMENT) references CATEGORY(CATEGORY),
		PRODUCT_MANUFACTURERID_MANUFACTURER_MANUFACTURERID as PRODUCT(MANUFACTURERID) references MANUFACTURER(MANUFACTURERID),
		SALESFACT_DATE_DATE_DATE as SALESFACT(COL_DATE) references COL_DATE(COL_DATE),
		SALESFACT_ZIP_GEO_ZIP as SALESFACT(ZIP) references GEO(ZIP),
		SALESFACT_PRODUCTID_PRODUCT_PRODUCTID as SALESFACT(PRODUCTID) references PRODUCT(PRODUCTID),
		SENTIMENT_DATE_DATE_DATE as SENTIMENT(COL_DATE) references COL_DATE(COL_DATE),
		SENTIMENT_ZIP_GEO_ZIP as SENTIMENT(ZIP) references GEO(ZIP),
		SENTIMENT_MANUFACTURERID_MANUFACTURER_MANUFACTURERID as SENTIMENT(MANUFACTURERID) references MANUFACTURER(MANUFACTURERID)
	)
	dimensions (
		CATEGORY.CATEGORY as CATEGORY."CATEGORY",
		CATEGORY.CHANNEL as CATEGORY."CHANNEL" with synonyms=('Total Sales by Product and Channel','Total Sales by Channel Over Time','Total Sales by Channel and State','Sales and ROI Over Time','Total Sales by City'),
		CATEGORY.SORT as CATEGORY."SORT",
		COL_DATE.COL_DATE as COL_DATE."COL_DATE" with synonyms=('Total Sales by Product and Channel','Total Sales by Channel Over Time','Total Sales','Online Sales','Social Media Sales','Stores Sales','Outlet Sales','Total Sales by Channel and State','Sales and ROI Over Time'),
		COL_DATE.MONTHNO as COL_DATE."MONTHNO" with synonyms=('Month No'),
		COL_DATE.MONTHNAME as COL_DATE."MONTHNAME" with synonyms=('Month Name'),
		COL_DATE.MONTHID as COL_DATE."MONTHID" with synonyms=('Month Id'),
		COL_DATE.MONTH as COL_DATE."MONTH",
		COL_DATE.QUARTER as COL_DATE."QUARTER",
		COL_DATE.YEAR as COL_DATE."YEAR",
		COL_DATE.RUNNINGMONTHS as COL_DATE."RUNNINGMONTHS" with synonyms=('Running Months'),
		COL_DATE.RUNNING_YEAR as COL_DATE."RUNNING_YEAR" with synonyms=('% Units Market Share R12M and % Units Market Share by Month','Total Sales by Product and Channel','Total Sales by Channel Over Time','Total Sales','Online Sales','Social Media Sales','Stores Sales','Outlet Sales','Total Sales by Channel and State','Sales and ROI Over Time','Total Sales by City'),
		COL_DATE.RUNNING_MONTHS as COL_DATE."RUNNING_MONTHS",
		COL_DATE.ROLLING_PERIOD as COL_DATE."ROLLING_PERIOD",
		COL_DATE.ROLLING_PERIOD_SORT as COL_DATE."ROLLING_PERIOD_SORT",
		COL_DATE.MONTHINDEX as COL_DATE."MONTHINDEX" with synonyms=('Month Index'),
		COL_DATE.MONTHS as COL_DATE."MONTHS" with synonyms=('Total Sales by Channel Over Time','Sales and ROI Over Time'),
		GEO.ZIP as GEO."ZIP",
		GEO.CITY as GEO."CITY" with synonyms=('Total Sales by City'),
		GEO.STATE as GEO."STATE" with synonyms=('Outlet Sales','Stores Sales','Social Media Sales','Online Sales','Total Sales','Total Sales by Channel and State','Total Sales by City'),
		GEO.REGION as GEO."REGION",
		GEO.DISTRICT as GEO."DISTRICT",
		INDICATORS.SORT_2 as INDICATORS."SORT",
		INDICATORS.STATUS as INDICATORS."STATUS",
		INDICATORS.IMAGE as INDICATORS."IMAGE",
		KPI.KPI as KPI."KPI" with synonyms=('Total Sales','Online Sales','Social Media Sales','Stores Sales','Outlet Sales'),
		KPI.CATEGORY_2 as KPI."CATEGORY",
		MANUFACTURER.MANUFACTURERID as MANUFACTURER."MANUFACTURERID" with synonyms=('Manufacturer Id'),
		MANUFACTURER.MANUFACTURER as MANUFACTURER."MANUFACTURER",
		MANUFACTURER.MFGISVANARSDEL as MANUFACTURER."MFGISVANARSDEL" with synonyms=('Mfgis Van Arsdel'),
		PRODUCT.MANUFACTURER_2 as PRODUCT."MANUFACTURER",
		PRODUCT.CATEGORY_3 as PRODUCT."CATEGORY" with synonyms=('Total Sales by Product and Channel','Total Sales by Channel Over Time','Total Sales','Online Sales','Social Media Sales','Stores Sales','Outlet Sales','Total Sales by Channel and State','Sales and ROI Over Time'),
		PRODUCT.SEGMENT as PRODUCT."SEGMENT" with synonyms=('Total Sales','Online Sales','Social Media Sales','Stores Sales','Outlet Sales'),
		PRODUCT.PRODUCT as PRODUCT."PRODUCT" with synonyms=('Total Sales by Product and Channel'),
		PRODUCT.PRODUCTID as PRODUCT."PRODUCTID" with synonyms=('Product Id'),
		PRODUCT.ISVANARSDEL as PRODUCT."ISVANARSDEL" with synonyms=('Is Van Arsdel'),
		PRODUCT.ISCOMPETEHIDE as PRODUCT."ISCOMPETEHIDE" with synonyms=('Is Compete Hide'),
		PRODUCT.MANUFACTURERID_2 as PRODUCT."MANUFACTURERID" with synonyms=('Manufacturer Id'),
		PRODUCT.ISCOMPETE as PRODUCT."ISCOMPETE" with synonyms=('Is Compete'),
		SALESFACT.PRODUCTID_2 as SALESFACT."PRODUCTID" with synonyms=('Product Id'),
		SALESFACT.COL_DATE_2 as SALESFACT."COL_DATE",
		SALESFACT.ZIP_2 as SALESFACT."ZIP",
		SALESFACT.UNITS as SALESFACT."UNITS",
		SALESFACT.REVENUE as SALESFACT."REVENUE",
		SENTIMENT.DATEID as SENTIMENT."DATEID" with synonyms=('Date Id'),
		SENTIMENT.STATEID as SENTIMENT."STATEID" with synonyms=('State Id'),
		SENTIMENT.MANUFACTURERID_3 as SENTIMENT."MANUFACTURERID" with synonyms=('Manufacturer Id'),
		SENTIMENT.SCORE as SENTIMENT."SCORE",
		SENTIMENT.MANUFACTURER_3 as SENTIMENT."MANUFACTURER",
		SENTIMENT.COL_DATE_3 as SENTIMENT."COL_DATE",
		SENTIMENT.STATE_2 as SENTIMENT."STATE",
		SENTIMENT.ZIP_3 as SENTIMENT."ZIP",
		SENTIMENT.PRODUCTID_3 as SENTIMENT."PRODUCTID" with synonyms=('Product Id')
	)
	metrics (
		PRODUCT.COUNT_OF_PRODUCT as COUNT(PRODUCT.PRODUCT),
		PRODUCT.NEWCOUNT_OF_PRODUCT as COUNT_IF(PRODUCT."PRODUCT" IS NULL) with synonyms=('New Count Of Product'),
		PRODUCT.NEWNEWCOUNT_OF_PRODUCT as COUNT_IF(PRODUCT."PRODUCT" IS NULL) with synonyms=('New New Count Of Product'),
		SALESFACT.TOTAL_UNITS as SUM(SALESFACT.UNITS::FLOAT),
		SALESFACT.SALES_DOL as SUM(SALESFACT.REVENUE::FLOAT),
		SENTIMENT.SENTIMENT as AVG(SENTIMENT.SCORE),
		SALESFACT.TOTAL_UNITS_YTD as SUM(CASE WHEN "DATE_DATE" >= DATE_TRUNC('YEAR', SALESFACT."MAX_DATE") AND "DATE_DATE" <= SALESFACT."MAX_DATE" THEN SALESFACT."UNITS" ELSE 0 END::FLOAT),
		SALESFACT.TOTAL_CATEGORY_VOLUME as (SUM(SALESFACT.UNITS::FLOAT)) with synonyms=('Total Sales by Product and Channel','Total Sales by Channel Over Time','Total Sales by Channel and State','Sales and ROI Over Time','Total Sales by City'),
		SALESFACT.TOTAL_COMPETE_VOLUME as SUM(CASE WHEN SALESFACT.PRODUCT_ISVANARSDEL = 'No' THEN SALESFACT.UNITS ELSE 0 END::FLOAT),
		SALESFACT.PCT_CATEGORY_COMPETE_SHARE as FLOOR(DIV0((SUM(CASE WHEN SALESFACT.PRODUCT_ISVANARSDEL = 'No' THEN SALESFACT.UNITS ELSE 0 END::FLOAT)), (SUM(SALESFACT.UNITS::FLOAT))) * 100),
		SALESFACT.TOTAL_UNITS_SPLY as SUM(CASE WHEN DATE_PART('YEAR', COL_DATE.COL_DATE) = DATE_PART('YEAR', DATEADD(YEAR, -1, SALESFACT.MAX_DATE)) AND COL_DATE.COL_DATE BETWEEN DATEADD(YEAR, -1, DATE_TRUNC('YEAR', SALESFACT.MAX_DATE)) AND DATEADD(YEAR, -1, SALESFACT.MAX_DATE) THEN SALESFACT.UNITS ELSE 0 END::FLOAT),
		SALESFACT.TOTAL_UNITS_YTD_SPLY as CAST(NULL AS DOUBLE),
		SALESFACT.SENTIMENT_GAP as AVG(CASE WHEN SALESFACT.MANUFACTURER_MFGISVANARSDEL = 'Yes' THEN SALESFACT.SENTIMENT_SCORE ELSE NULL END) - AVG(CASE WHEN SALESFACT.MANUFACTURER_MFGISVANARSDEL = 'No' THEN SALESFACT.SENTIMENT_SCORE ELSE NULL END),
		SALESFACT.SUM_OF_UNITS as SUM(SALESFACT.UNITS::FLOAT),
		SALESFACT.SUM_OF_REVENUE as SUM(SALESFACT.REVENUE::FLOAT),
		SALESFACT.ATINDICATOR01 as CASE WHEN SALESFACT."PCT_CATEGORY_COMPETE_SHARE" < 0.55 THEN 1 ELSE CASE WHEN SALESFACT."PCT_CATEGORY_COMPETE_SHARE" > 0.6 THEN 3 ELSE 2 END END with synonyms=('Total Sales by Product and Channel'),
		SENTIMENT.ATINDICATOR04 as CASE WHEN SENTIMENT."SENTIMENT" < 65 THEN 1 ELSE CASE WHEN SENTIMENT."SENTIMENT" > 67 THEN 3 ELSE 2 END END,
		SALESFACT.ATINDICATOR05 as CASE WHEN SALESFACT."SENTIMENT_GAP" < 15 THEN 1 ELSE CASE WHEN SALESFACT."SENTIMENT_GAP" > 25 THEN 3 ELSE 2 END END,
		SENTIMENT.ATINDICATOR04A as CASE WHEN SENTIMENT."ATINDICATOR04" = 1 THEN 'Low Sentiment Rate' ELSE CASE WHEN SENTIMENT."ATINDICATOR04" = 3 THEN 'High Sentiment Rate' ELSE 'Medium Sentiment Rate' END END,
		SALESFACT.ATINDICATOR05A as CASE WHEN SALESFACT."ATINDICATOR05" = 1 THEN 'Low Sentiment Gap' ELSE CASE WHEN SALESFACT."ATINDICATOR05" = 3 THEN 'High Sentiment Gap' ELSE 'Medium Sentiment Gap' END END,
		SENTIMENT.SUM_OF_SCORE as SUM(SENTIMENT.SCORE::FLOAT),
		SENTIMENT.AVERAGE_OF_SCORE as AVG(SENTIMENT.SCORE),
		SENTIMENT.NEW_DEMO_MEASURE as AVG(SENTIMENT.SCORE)
	);