from semabridge.connectors.semantic_ddl_sanitizer import SemanticDDLSanitizer


class _San:
    _reserved = set()

    @staticmethod
    def sanitize_column(v: str) -> str:
        return str(v or "").upper()


def test_comp_sf_hardening_applies_critical_rewrites():
    sanitizer = SemanticDDLSanitizer(_San())
    ddl = """
CREATE OR REPLACE SEMANTIC VIEW "DB"."PUBLIC"."X"
TABLES (
  SALESFACT AS "DB"."PUBLIC"."SALESFACT" PRIMARY KEY ("PRODUCTID", "ZIP"),
  COL_DATE AS "DB"."PUBLIC"."DATE" PRIMARY KEY ("MONTHID"),
  SENTIMENT AS "DB"."PUBLIC"."SENTIMENT" PRIMARY KEY ("ZIP", "MANUFACTURERID")
)
RELATIONSHIPS (
  PRODUCT_SEGMENT_CATEGORY_CATEGORY AS PRODUCT ("SEGMENT") REFERENCES CATEGORY ("CATEGORY"),
  SALESFACT_DATE_DATE_DATE AS SALESFACT ("COL_DATE") REFERENCES COL_DATE ("MONTHID"),
  SENTIMENT_DATE_DATE_DATE AS SENTIMENT ("COL_DATE") REFERENCES COL_DATE ("MONTHID")
)
DIMENSIONS (
  MANUFACTURER."MANUFACTURER_802B" AS MANUFACTURER."MANUFACTURER" WITH SYNONYMS=('Producer','Maker'),
  KPI."CATEGORY_791F" AS KPI."CATEGORY" WITH SYNONYMS=('Type','Class','Grouping'),
  CATEGORY."SORT_3810" AS CATEGORY."SORT",
  CATEGORY."CATEGORY_AC82" AS CATEGORY."CATEGORY_AC82",
  CATEGORY."CHANNEL_F73C" AS CATEGORY."CHANNEL_F73C",
  CATEGORY."SORT_234C" AS CATEGORY."SORT_234C"
)
METRICS (
  SALESFACT."TOTAL_VANARSDEL_UNITS" AS 0,
  SALESFACT."TOTAL_OTHER_UNITS" AS 0,
  SALESFACT."TOTAL_CATEGORY_VOLUME" AS 0,
  SALESFACT."TOTAL_COMPETE_VOLUME" AS 0,
  SALESFACT."CATEGORY_COMPETE_SHARE" AS 0,
  SALESFACT."UNITS_MARKET_SHARE" AS 0,
  SALESFACT."INDICATOR01" AS 0,
  SALESFACT."INDICATOR04" AS 0,
  SALESFACT."INDICATOR04A" AS 0,
  SALESFACT."INDICATOR05" AS 0,
  SALESFACT."INDICATOR05A" AS 0
);
"""

    out = sanitizer.sanitize_structure(ddl)
    assert 'PRIMARY KEY ("COL_DATE")' in out
    assert 'PRIMARY KEY ("PRODUCTID", "COL_DATE", "ZIP")' in out
    assert 'PRIMARY KEY ("DATEID")' in out
    assert 'PRODUCT_SEGMENT_CATEGORY_CATEGORY' not in out
    assert 'REFERENCES COL_DATE ("COL_DATE")' in out
    assert 'MANUFACTURER."MANUFACTURER_802B"' not in out
    assert 'CATEGORY."CATEGORY_AC82"' not in out
    assert 'SENTIMENT."SCORE" AS SENTIMENT."SCORE"' in out
    assert 'SALESFACT."TOTAL_VANARSDEL_UNITS" AS SUM(CASE WHEN PRODUCT.ISVANARSDEL = \'Yes\'' in out
    assert 'SALESFACT."INDICATOR04" AS' not in out
    assert 'SENTIMENT."INDICATOR04" AS CASE WHEN AVG(SENTIMENT.SCORE::FLOAT)' in out
    assert ",," not in out


def test_comp_sf_hardening_handles_unquoted_entity_style_from_runtime():
    sanitizer = SemanticDDLSanitizer(_San())
    ddl = """
CREATE OR REPLACE SEMANTIC VIEW SEMABRIDGE.PUBLIC.COMPETITIVE_MARKETING_ANALYSIS_SEMANTIC
TABLES (
  COL_DATE as SEMABRIDGE.PUBLIC.DATE primary key (COL_DATE),
  SEMABRIDGE.PUBLIC.SALESFACT primary key (PRODUCTID,COL_DATE,ZIP)
)
DIMENSIONS (
  MANUFACTURER.MANUFACTURER_802B as MANUFACTURER."MANUFACTURER" with synonyms = ('Producer','Maker'),
  KPI.CATEGORY_791F as KPI."CATEGORY" with synonyms = ('Type','Class','Grouping'),
  CATEGORY.CHANNEL as CATEGORY."CHANNEL",
  CATEGORY.SORT as CATEGORY."SORT"
)
METRICS (
  SALESFACT.TOTAL_VANARSDEL_UNITS as 0 with synonyms = ('Total Van Arsdel Units'),
  SALESFACT.TOTAL_OTHER_UNITS as 0 with synonyms=('Sum Other Units'),
  SALESFACT.TOTAL_CATEGORY_VOLUME as 0 with synonyms=('Sum Category Volume'),
  SALESFACT.TOTAL_COMPETE_VOLUME as 0 with synonyms=('Sum Compete Volume'),
  SALESFACT.CATEGORY_COMPETE_SHARE as 0 with synonyms=('Category Compete Share'),
  SALESFACT.UNITS_MARKET_SHARE as 0 with synonyms=('Units Market Share'),
  SALESFACT.INDICATOR01 as 0 with synonyms=('Indicator01')
);
"""

    out = sanitizer.sanitize_structure(ddl)
    assert "MANUFACTURER_802B" not in out
    assert "CATEGORY_791F" not in out
    assert "SALESFACT.TOTAL_VANARSDEL_UNITS as 0" not in out
    assert "SALESFACT.TOTAL_OTHER_UNITS as 0" not in out
    assert "SALESFACT.TOTAL_CATEGORY_VOLUME as 0" not in out
    assert "SALESFACT.TOTAL_COMPETE_VOLUME as 0" not in out
    assert "SALESFACT.CATEGORY_COMPETE_SHARE as 0" not in out
    assert "SALESFACT.UNITS_MARKET_SHARE as 0" not in out
    assert "SALESFACT.INDICATOR01 as 0" not in out
    assert "MANUFACTURER.MANUFACTURER as MANUFACTURER.\"MANUFACTURER\" with synonyms=('Producer','Maker')" in out
    assert "KPI.CATEGORY as KPI.\"CATEGORY\" with synonyms=('Type','Class','Grouping')" in out
    assert "SALESFACT.TOTAL_VANARSDEL_UNITS as SUM(CASE WHEN PRODUCT.ISVANARSDEL = 'Yes' THEN SALESFACT.UNITS ELSE 0 END::FLOAT)" in out
    assert "SALESFACT.TOTAL_OTHER_UNITS as SUM(CASE WHEN PRODUCT.ISVANARSDEL = 'No' THEN SALESFACT.UNITS ELSE 0 END::FLOAT)" in out
    assert "SALESFACT.TOTAL_CATEGORY_VOLUME as SUM(SALESFACT.UNITS::FLOAT)" in out
    assert "SALESFACT.TOTAL_COMPETE_VOLUME as SUM(CASE WHEN PRODUCT.ISVANARSDEL = 'No' THEN SALESFACT.UNITS ELSE 0 END::FLOAT)" in out
    assert "SALESFACT.CATEGORY_COMPETE_SHARE as FLOOR(SUM(CASE WHEN PRODUCT.ISVANARSDEL = 'No' THEN SALESFACT.UNITS ELSE 0 END::FLOAT) / NULLIF(SUM(SALESFACT.UNITS::FLOAT), 0) * 100)" in out
    assert "SALESFACT.UNITS_MARKET_SHARE as CASE WHEN SUM(SALESFACT.UNITS::FLOAT) = 0 THEN 0 ELSE SUM(CASE WHEN PRODUCT.ISVANARSDEL = 'Yes' THEN SALESFACT.UNITS ELSE 0 END::FLOAT) / SUM(SALESFACT.UNITS::FLOAT) END" in out
    assert "SALESFACT.INDICATOR01 as CASE WHEN SUM(CASE WHEN PRODUCT.ISVANARSDEL='No' THEN SALESFACT.UNITS ELSE 0 END::FLOAT) / NULLIF(SUM(SALESFACT.UNITS::FLOAT), 0) < 0.55 THEN 1 WHEN SUM(CASE WHEN PRODUCT.ISVANARSDEL='No' THEN SALESFACT.UNITS ELSE 0 END::FLOAT) / NULLIF(SUM(SALESFACT.UNITS::FLOAT), 0) > 0.60 THEN 3 ELSE 2 END" in out


def test_comp_sf_hardening_does_not_inject_sentiment_clauses_without_sentiment_table():
    sanitizer = SemanticDDLSanitizer(_San())
    ddl = """
CREATE OR REPLACE SEMANTIC VIEW "DB"."PUBLIC"."X"
TABLES (
  SALESFACT AS "DB"."PUBLIC"."SALESFACT" PRIMARY KEY ("PRODUCTID")
)
DIMENSIONS (
  SALESFACT."PRODUCTID" AS SALESFACT."PRODUCTID"
)
METRICS (
  SALESFACT."TOTAL_CATEGORY_VOLUME" AS 0
);
"""

    out = sanitizer.sanitize_structure(ddl)

    assert 'SENTIMENT."SCORE" AS SENTIMENT."SCORE"' not in out
    assert 'SENTIMENT."INDICATOR04"' not in out
    assert 'SENTIMENT."INDICATOR05"' not in out
