"""
Repository interface contracts (Python Protocols).

These define the boundary between the application layer and infrastructure.
Concrete SQLAlchemy implementations live in repository/orm/.
"""
from __future__ import annotations
from typing import Any, Optional, Protocol, runtime_checkable


@runtime_checkable
class IUserRepository(Protocol):
    def get_by_id(self, user_id: int) -> Optional[Any]: ...
    def get_by_email(self, email: str) -> Optional[Any]: ...
    def create(self, email: str, hashed_password: str, username: str) -> Any: ...
    def update_password(self, user_id: int, hashed_password: str) -> None: ...


@runtime_checkable
class IAccountRepository(Protocol):
    def get_by_id(self, account_id: int, owner_id: int) -> Optional[Any]: ...
    def list_for_owner(self, owner_id: int) -> list[Any]: ...
    def create(self, owner_id: int, **kwargs: Any) -> Any: ...
    def delete(self, account_id: int, owner_id: int) -> None: ...


@runtime_checkable
class IProjectRepository(Protocol):
    def get(self, project_id: str) -> Optional[Any]: ...
    def list(self, folder_id: Optional[str] = None, owner_id: Optional[int] = None) -> list[Any]: ...
    def create(self, **kwargs: Any) -> Any: ...
    def update(self, project_id: str, **kwargs: Any) -> Optional[Any]: ...
    def delete(self, project_id: str) -> None: ...


@runtime_checkable
class IRunRepository(Protocol):
    def get(self, run_id: str) -> Optional[Any]: ...
    def list_for_project(self, project_id: str, limit: int = 50) -> list[Any]: ...
    def create(self, **kwargs: Any) -> Any: ...
    def update_status(self, run_id: str, status: str, **kwargs: Any) -> None: ...


@runtime_checkable
class ISnapshotRepository(Protocol):
    def get(self, snapshot_id: str) -> Optional[Any]: ...
    def list_for_project(self, project_id: str) -> list[Any]: ...
    def create(self, **kwargs: Any) -> Any: ...
    def delete(self, snapshot_id: str) -> None: ...


@runtime_checkable
class IMappingRepository(Protocol):
    def list_for_project(self, project_id: str) -> list[Any]: ...
    def save(self, project_id: str, mappings: list[Any]) -> None: ...
    def delete_for_project(self, project_id: str) -> None: ...


@runtime_checkable
class ICredentialRepository(Protocol):
    def get(self, key: str, owner_id: int) -> Optional[str]: ...
    def store(self, key: str, value: str, owner_id: int) -> None: ...
    def delete(self, key: str, owner_id: int) -> None: ...


@runtime_checkable
class IModelVersionRepository(Protocol):
    def get(self, version_id: str) -> Optional[Any]: ...
    def list_for_project(self, project_id: str, limit: int = 50) -> list[Any]: ...
    def create(self, **kwargs: Any) -> Any: ...
