"""Per-run Markdown summary report — written for a business stakeholder,
not a developer.

Reuses existing pipeline output rather than recomputing anything:

- Header / status / source(s)         -> the ``run`` dict (project_shared's
  in-memory run record), already fully populated by the time
  ``_perform_project_run`` reaches its ``finally`` block.
- What was found / what converted     -> the persisted SML snapshot blob
  (``ModelRepository.get_snapshot(sml_snapshot_id).sml_blob``), the same
  blob ``snapshot_service.get_snapshot_report_compat`` already parses for
  the existing snapshot-report endpoint.
- What was dropped, and why           -> ``RunSummary.dropped_entities``
  (``DropRecord`` list), already reconciled by
  ``core/engine/finalize.py::_reconcile_dropped_entities`` and copied onto
  the run dict by the time this module runs.
- AI-assisted risk/confidence         -> ``SMLMetric.complexity_tier`` == 5,
  ``llm_self_reported_confidence``, ``validation_notes`` and the same
  risky-DAX-pattern check ``project_mapping_engine._compute_static_risk_tier``
  already uses for the dry-run page (imported, not reimplemented).

Every string here is written for someone who has never heard of a "drop
ledger" or a "translation tier" — no pipeline/internal terminology reaches
the rendered file. See ``_REASON_RULES``/``_STAGE_FALLBACKS`` for the
plain-language translation of every ``drop_ledger.record(...)`` reason in
the codebase as of writing (grep-verified against every call site).
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# Run reports get their own, run_id-scoped directory -- unlike the existing
# `output/<target>/<project_id>/...` convention (engine.py's
# _model_output_dir), which is project-keyed and gets overwritten by every
# new run. A report must survive being generated by a run that a later run
# then supersedes.
REPORTS_ROOT = Path("output") / "reports"


# ---------------------------------------------------------------------------
# Drop-reason -> plain-language translation
# ---------------------------------------------------------------------------
# (substring to match against the lowercased raw reason, plain-English
# sentence). Checked in order, first match wins. This list was built by
# grepping every drop_ledger.record(...)/DropRecord(...) call site in the
# codebase (dimensions_clause_builder.py, metrics_clause_builder.py,
# relationships_clause_builder.py, snowflake_emitter.py, tmsl_to_osi.py,
# tmsl_to_sml.py, run_service.py's post-deploy reconciliation) -- every
# reason string that exists today matches one of these rules. Anything that
# doesn't match (a future call site, or wording drift) falls through to
# _STAGE_FALLBACKS below, so the report never leaks a raw internal reason.
_REASON_RULES: List[Tuple[str, str]] = [
    (
        "auto-generated power bi",
        "An automatic calendar table Power BI creates behind the scenes. "
        "It isn't part of your real business data.",
    ),
    (
        "calculation group",
        "An advanced Power BI authoring feature not yet supported by this "
        "conversion. It doesn't represent a business metric on its own.",
    ),
    (
        "duplicate physical-column",
        "A duplicate copy of this field (differing only in upper/lower "
        "case) was found in the source. One copy was kept automatically.",
    ),
    (
        "null-cast placeholder",
        "This calculation's formula could not be converted, and there was "
        "no original definition left to try again with.",
    ),
    (
        "deterministic, rule-based, and llm translation tiers were all",
        "This calculation's formula was too complex or unusual for either "
        "our standard conversion rules or AI assistance to handle.",
    ),
    (
        "ambiguous in dataset",
        "This field's name matches more than one column in the underlying "
        "data, and we can't safely tell which one was intended.",
    ),
    (
        "not found in the live snowflake schema",
        "This field no longer exists in the connected database, so "
        "anything depending on it couldn't be included.",
    ),
    (
        "no live snowflake schema was fetched",
        "We couldn't confirm this field still exists in the database at "
        "the time of this run, so it was left out to be safe.",
    ),
    (
        "no live schema was",
        "A date field this calculation depends on couldn't be checked "
        "against the connected database, so it was left out to avoid a "
        "possibly-wrong result.",
    ),
    (
        "no tables alias",
        "This calculation depends on data that isn't available in this "
        "semantic model.",
    ),
    (
        "non-scalar construct",
        "This calculation's formula needs a type of data lookup the "
        "destination system can't run directly.",
    ),
    (
        "contains a subquery",
        "This calculation's formula needs a nested lookup the destination "
        "system can't run directly.",
    ),
    (
        "type mismatch",
        "This calculation combines two incompatible kinds of data (for "
        "example, a date and a plain number). It needs to be corrected "
        "before it can be included.",
    ),
    (
        "virtual power bi measures table",
        "This calculation lives in a Power BI area with no data columns "
        "of its own, and it couldn't be linked back to the real data "
        "table it depends on.",
    ),
    (
        "could not resolve all virtual measures-table",
        "This calculation refers to a data field that couldn't be matched "
        "to anything in the source model.",
    ),
    (
        "could not be resolved after normalization",
        "This calculation refers to a data field that couldn't be matched "
        "to anything in the source model.",
    ),
    (
        "no source_column+aggregation",
        "This calculation has no underlying formula or data field "
        "defined, so there was nothing to convert.",
    ),
    (
        "by-design excluded",
        "Excluded intentionally — this item isn't meant to produce a "
        "reportable value on its own.",
    ),
    (
        "unresolvable dataset aliases",
        "A connection between two tables that this depends on couldn't "
        "be matched to real columns in the source data.",
    ),
    (
        "resolved to empty after physical column resolution",
        "A connection between two tables that this depends on couldn't "
        "be matched to real columns in the source data.",
    ),
    (
        "deployment aborted mid-ddl-execution",
        "The deployment was interrupted partway through, after some "
        "changes had already been applied to the destination. We "
        "recommend verifying the destination before re-running.",
    ),
    (
        "rejected this identifier",
        "The destination database rejected this item's name, and it "
        "couldn't be automatically corrected.",
    ),
    (
        "absent from both the deployed semantic",
        "This calculation looked ready to deploy but couldn't be "
        "confirmed as live afterward — possibly lost silently during "
        "deployment. We recommend re-running or checking manually.",
    ),
]

# Per-stage safety net for any reason that doesn't match a rule above, keyed
# on the same DropStage string values RunSummary.dropped_entities carries
# (plus "reconciliation", the one ad-hoc stage run_service.py adds itself).
_STAGE_FALLBACKS: Dict[str, str] = {
    "extraction": "Excluded while reading the source file.",
    "dax_translation": "This calculation's formula could not be converted into a working query.",
    "schema_validation": "This calculation depends on data that isn't available yet.",
    "ddl_emission": "This item couldn't be built in the format the destination requires.",
    "ddl_deployment": "The destination database rejected this item during deployment.",
    "reconciliation": "This item couldn't be confirmed as successfully deployed.",
}

# Plain-language group headings for the same stages -- used instead of the
# raw stage name so the report never shows "DropStage" jargon while still
# preserving the useful "roughly when did this happen" grouping.
_STAGE_GROUP_LABELS: Dict[str, str] = {
    "extraction": "While reading your source file",
    "dax_translation": "While converting calculations",
    "schema_validation": "While checking against your database",
    "ddl_emission": "While preparing calculations for deployment",
    "ddl_deployment": "While deploying to {target}",
    "reconciliation": "After deployment, during verification",
}
_STAGE_ORDER = [
    "extraction",
    "dax_translation",
    "schema_validation",
    "ddl_emission",
    "ddl_deployment",
    "reconciliation",
]

# advisory_categories is a stable code, not free text -- REAL_DEPLOY_ONLY_
# ADVISORY_CATEGORIES in project_mapping_engine.py is a one-entry set today
# (ADVISORY_CATEGORY_UNREACHABLE_DIMENSION), so this dict has one real entry
# plus a generic fallback for whatever category is added next.
_ADVISORY_FALLBACK_MESSAGE = (
    "This calculation was flagged with a structural note during "
    "conversion. We recommend double-checking this number."
)


def _advisory_category_messages() -> Dict[str, str]:
    from semabridge.converter.dax_ast_parser import ADVISORY_CATEGORY_UNREACHABLE_DIMENSION

    return {
        ADVISORY_CATEGORY_UNREACHABLE_DIMENSION: (
            "This calculation references data from a different part of "
            "your source model that isn't connected to it. It converted, "
            "but we recommend double-checking this number."
        ),
    }


def humanize_drop_reason(record: Dict[str, Any]) -> str:
    """Translate one DropRecord dict's `reason` into a plain sentence."""
    reason = str(record.get("reason") or "")
    stage = str(record.get("stage") or "")
    lowered = reason.lower()
    for needle, plain in _REASON_RULES:
        if needle in lowered:
            return plain
    return _STAGE_FALLBACKS.get(
        stage, "This item could not be included in the converted model."
    )


def stage_group_label(stage: str, target_label: str = "the destination") -> str:
    template = _STAGE_GROUP_LABELS.get(stage, "During conversion")
    return template.format(target=target_label) if "{target}" in template else template


# ---------------------------------------------------------------------------
# SML snapshot loading / metric classification
# ---------------------------------------------------------------------------

def _load_snapshot_data(sml_snapshot_id: Optional[str]) -> Optional[Dict[str, Any]]:
    """Load a persisted SML snapshot's datasets/metrics/relationships.

    One extra DB read, exactly the pattern
    snapshot_service.get_snapshot_report_compat already uses to recompute
    total_models/total_columns for the existing snapshot-report endpoint --
    the live SMLModel object itself is discarded once ExecutionEngine.execute()
    returns, so this is the only place per-metric complexity_tier/
    llm_self_reported_confidence/advisory data still exists after the run.
    """
    if not sml_snapshot_id:
        return None
    try:
        from semabridge.repository.model_repository import ModelRepository

        snap = ModelRepository().get_snapshot(str(sml_snapshot_id))
    except Exception:
        logger.debug(
            "Run report: could not load snapshot %s", sml_snapshot_id, exc_info=True
        )
        return None
    if not snap or not isinstance(snap.sml_blob, dict):
        return None
    blob = snap.sml_blob
    datasets = [d for d in (blob.get("datasets") or []) if isinstance(d, dict)]
    return {
        "dataset_count": len(datasets),
        "column_count": sum(len(d.get("columns") or []) for d in datasets),
        "relationship_count": len(blob.get("relationships") or []),
        "metrics": [m for m in (blob.get("metrics") or []) if isinstance(m, dict)],
    }


def _classify_metrics(sml_metrics: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
    """Split a snapshot's metrics into Standard / Standard-with-a-flag /
    AI-assisted, reusing the same risky-DAX-pattern check the dry-run page's
    three-tier risk label already uses (project_mapping_engine.py) rather
    than reimplementing it.

    "known risky pattern" in _compute_static_risk_tier is structurally
    reachable ONLY inside its `if is_tier5:` branch -- so that signal is
    folded into the AI-assisted entries below, not a separate section.
    advisory_notes/advisory_categories (osi_to_sml.py's unreachable-
    dimension check), however, run over every metric regardless of tier --
    so a Standard-conversion metric can carry a real flag too, and does get
    one here.
    """
    from semabridge.api.services.project_mapping_engine import _has_known_risky_dax_pattern

    advisory_messages = _advisory_category_messages()
    standard: List[Dict[str, Any]] = []
    ai_assisted: List[Dict[str, Any]] = []

    for metric in sml_metrics:
        if not metric.get("sync_enabled", True):
            continue  # not successfully converted -- appears in the drop ledger instead
        name = metric.get("unique_name") or metric.get("label") or "Unnamed calculation"
        tier = metric.get("complexity_tier") or 1
        categories = metric.get("advisory_categories") or []
        notes_present = bool(metric.get("advisory_notes"))
        advisory_msgs = [advisory_messages.get(cat, _ADVISORY_FALLBACK_MESSAGE) for cat in categories]
        if not advisory_msgs and notes_present:
            advisory_msgs = [_ADVISORY_FALLBACK_MESSAGE]

        if tier == 5:
            is_risky = bool(metric.get("validation_notes")) or _has_known_risky_dax_pattern(
                str(metric.get("expression") or "")
            )
            ai_assisted.append(
                {
                    "name": name,
                    "confidence": metric.get("llm_self_reported_confidence"),
                    "risky": is_risky,
                    "advisory_msgs": advisory_msgs,
                }
            )
        else:
            standard.append({"name": name, "advisory_msgs": advisory_msgs})

    return {"standard": standard, "ai_assisted": ai_assisted}


# ---------------------------------------------------------------------------
# Source description (source-type-agnostic: local PBIX single/multi-file,
# Fabric)
# ---------------------------------------------------------------------------

def _parse_project_cfg(project_cfg: str) -> Dict[str, Any]:
    # Deliberately re-implemented here (not imported from run_service.py's
    # _compat_parse_project_cfg_dict) to avoid a circular import --
    # run_service.py imports write_run_report from this module.
    import yaml

    try:
        parsed = yaml.safe_load(project_cfg or "") or {}
        return parsed if isinstance(parsed, dict) else {}
    except Exception:
        return {}


def _describe_source(project_cfg: str, run: Dict[str, Any]) -> Tuple[str, List[str]]:
    """Returns (source kind label, [one description per source file/dataset]).

    Reads the same source config every source type already funnels through
    (execution_config.SourceConfig / sync_execution_service._build_sync_jobs)
    -- nothing here branches on anything other than `type`.
    """
    parsed = _parse_project_cfg(project_cfg)
    source_cfg = parsed.get("source") if isinstance(parsed.get("source"), dict) else {}
    source_type = str(run.get("source_type") or source_cfg.get("type") or "").lower()

    if source_type == "pbix":
        pbix_path = source_cfg.get("pbix_path") or source_cfg.get("source_path") or source_cfg.get("file_path")
        if pbix_path:
            return "Local file", [Path(str(pbix_path)).name]
        models = source_cfg.get("models") or []
        if models:
            return "Local files", [Path(str(m)).name for m in models]
        labels = [
            str(r.get("model")) for r in (run.get("results") or [])
            if isinstance(r, dict) and r.get("model")
        ]
        return "Local file(s)", labels or ["(file name unavailable)"]

    if source_type == "fabric":
        dataset = source_cfg.get("dataset_id") or "(unknown dataset)"
        workspace = source_cfg.get("workspace_id")
        label = f"Fabric dataset {dataset}"
        if workspace:
            label += f" (workspace {workspace})"
        return "Microsoft Fabric", [label]

    if source_type == "snowflake":
        models = source_cfg.get("models") or []
        return "Snowflake", [str(m) for m in models] or ["(view name unavailable)"]

    return source_type.title() or "Unknown source", []


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

_STATUS_LABELS: Dict[str, Tuple[str, str]] = {
    "success": ("Completed successfully", "✅"),
    "warning": ("Completed — a few items need your attention", "⚠️"),
    "failed": ("Did not complete successfully", "❌"),
}


def _format_duration(duration_ms: Any) -> Optional[str]:
    try:
        total_seconds = int(float(duration_ms) / 1000)
    except (TypeError, ValueError):
        return None
    if total_seconds <= 0:
        return None
    minutes, seconds = divmod(total_seconds, 60)
    return f"{minutes}m {seconds}s" if minutes else f"{seconds}s"


def generate_run_report_markdown(run: Dict[str, Any], project_cfg: str) -> str:
    project_name = str(run.get("project_name") or run.get("project_id") or "Project")
    run_id = str(run.get("run_id") or run.get("id") or "unknown")
    status = str(run.get("status") or "failed").lower()
    status_label, status_icon = _STATUS_LABELS.get(status, ("Unknown", "❓"))
    source_kind, source_files = _describe_source(project_cfg, run)

    lines: List[str] = [
        f"# Run Report — {project_name}",
        "",
        f"**{status_icon} {status_label}**",
        "",
        f"- **Project:** {project_name}",
        f"- **Source:** {source_kind} — " + ", ".join(source_files or ["(unavailable)"]),
    ]
    started, completed = run.get("started_at"), run.get("completed_at")
    when = f"- **Started:** {started}" if started else ""
    if completed:
        when += f"  ·  **Completed:** {completed}"
    if when:
        lines.append(when)
    duration_label = _format_duration(run.get("duration_ms"))
    if duration_label:
        lines.append(f"- **Duration:** {duration_label}")
    lines.append(f"- **Run ID:** `{run_id}`")
    lines.append("")

    model_results = [r for r in (run.get("results") or []) if isinstance(r, dict)]
    if not model_results:
        top_summary = run.get("summary") if isinstance(run.get("summary"), dict) else {}
        if top_summary:
            model_results = [
                {
                    "model": project_name,
                    "summary": top_summary,
                    "dropped_entities": top_summary.get("dropped_entities") or [],
                }
            ]

    if not model_results:
        # Crashed before ExecutionEngine.execute() was even reached (bad
        # config, connection error, ...) -- there is no RunSummary at all,
        # so there is nothing to report on beyond the header and the error.
        lines.append("## What happened")
        lines.append("")
        lines.append("This run did not reach the point of reading your source file.")
        lines.append("")
        lines.append(f"**Error:** {run.get('error') or run.get('message') or 'Unknown error.'}")
        lines.append("")
        return "\n".join(lines)

    multi_model = len(model_results) > 1
    dataset_count = column_count = metric_count = relationship_count = 0
    standard: List[Dict[str, Any]] = []
    ai_assisted: List[Dict[str, Any]] = []
    dropped_by_stage: Dict[str, List[Dict[str, Any]]] = {}
    target_type = ""

    for result in model_results:
        model_label = str(result.get("model") or "")
        summary = result.get("summary") if isinstance(result.get("summary"), dict) else {}
        target_type = target_type or str(summary.get("target_type") or "")
        model_dropped = [
            d for d in (result.get("dropped_entities") or summary.get("dropped_entities") or [])
            if isinstance(d, dict)
        ]

        snap_data = _load_snapshot_data(summary.get("sml_snapshot_id"))
        if snap_data:
            # "Found in source" adds back by-design/schema-validation drops
            # so this reflects what was actually in the source file, not
            # just what survived into the final converted model.
            extraction_table_drops = sum(
                1 for d in model_dropped
                if d.get("stage") == "extraction" and d.get("entity_kind") == "table"
            )
            schema_column_drops = sum(
                1 for d in model_dropped
                if d.get("stage") == "schema_validation" and d.get("entity_kind") == "column"
            )
            emission_relationship_drops = sum(
                1 for d in model_dropped
                if d.get("stage") == "ddl_emission" and d.get("entity_kind") == "relationship"
            )
            dataset_count += snap_data["dataset_count"] + extraction_table_drops
            column_count += snap_data["column_count"] + schema_column_drops
            relationship_count += snap_data["relationship_count"] + emission_relationship_drops
            metric_count += len(snap_data["metrics"])

            classified = _classify_metrics(snap_data["metrics"])
            prefix = f"{model_label}: " if multi_model and model_label else ""
            for entry in classified["standard"]:
                standard.append({**entry, "name": f"{prefix}{entry['name']}"})
            for entry in classified["ai_assisted"]:
                ai_assisted.append({**entry, "name": f"{prefix}{entry['name']}"})

        for record in model_dropped:
            stage = str(record.get("stage") or "unknown")
            dropped_by_stage.setdefault(stage, []).append(record)

    # --- What we found in your source ------------------------------------
    lines.append("## What we found in your source")
    lines.append("")
    lines.append("| | Count |")
    lines.append("|---|---:|")
    lines.append(f"| Tables | {dataset_count} |")
    lines.append(f"| Columns | {column_count} |")
    lines.append(f"| Calculations | {metric_count} |")
    if relationship_count:
        lines.append(f"| Relationships between tables | {relationship_count} |")
    lines.append("")

    # --- What converted successfully --------------------------------------
    total_converted = len(standard) + len(ai_assisted)
    lines.append("## What converted successfully")
    lines.append("")
    lines.append(f"**{total_converted} of {metric_count} calculations converted.**")
    lines.append("")
    if standard:
        lines.append(f"### Standard conversion ({len(standard)})")
        lines.append("")
        lines.append("Converted automatically using SemaBridge's built-in conversion rules. No AI involved.")
        lines.append("")
        for entry in standard:
            if entry["advisory_msgs"]:
                lines.append(f"- **{entry['name']}** — _{entry['advisory_msgs'][0]}_")
            else:
                lines.append(f"- {entry['name']}")
        lines.append("")
    if ai_assisted:
        lines.append(f"### AI-assisted conversion ({len(ai_assisted)})")
        lines.append("")
        lines.append(
            "These calculations were too complex for our standard rules, so they "
            "were interpreted by AI instead. **We recommend verifying these numbers.**"
        )
        lines.append("")
        for entry in ai_assisted:
            sentence = (
                "This calculation was interpreted by AI rather than converted "
                "using a fixed rule — we recommend verifying this number."
            )
            confidence = entry.get("confidence")
            if isinstance(confidence, (int, float)):
                sentence += (
                    f" AI's own confidence in this calculation: "
                    f"{round(confidence * 100)}% (self-reported, not independently verified)."
                )
            if entry.get("risky"):
                sentence += " This calculation also matches a pattern that has caused problems before — please review it closely."
            for msg in entry.get("advisory_msgs") or []:
                sentence += f" {msg}"
            lines.append(f"- **{entry['name']}** — {sentence}")
        lines.append("")
    if not standard and not ai_assisted:
        lines.append("_Nothing converted successfully in this run._")
        lines.append("")

    # --- What we couldn't include, and why --------------------------------
    lines.append("## What we couldn't include, and why")
    lines.append("")
    if not dropped_by_stage:
        lines.append("Everything found in your source file was successfully converted and deployed.")
        lines.append("")
    else:
        target_label = target_type.title() if target_type else "the destination"
        ordered_stages = _STAGE_ORDER + [s for s in dropped_by_stage if s not in _STAGE_ORDER]
        for stage in ordered_stages:
            records = dropped_by_stage.get(stage)
            if not records:
                continue
            lines.append(f"### {stage_group_label(stage, target_label)} ({len(records)})")
            lines.append("")
            for record in records:
                name = record.get("entity_name") or "(unnamed)"
                plain = humanize_drop_reason(record)
                suffix = "  _(expected — not an error)_" if record.get("by_design") else ""
                lines.append(f"- **{name}** — {plain}{suffix}")
            lines.append("")

    return "\n".join(lines)


def write_run_report(run: Dict[str, Any], project_cfg: str) -> Optional[str]:
    """Render and persist the report for one run.

    Called unconditionally (success, partial, or failed) from
    _perform_project_run's `finally` block, so a failed run still produces
    a downloadable file. Never raises -- a reporting failure must not
    affect the run's own recorded outcome.
    """
    project_id = str(run.get("project_id") or "")
    run_id = str(run.get("run_id") or run.get("id") or "")
    if not project_id or not run_id:
        return None
    try:
        markdown = generate_run_report_markdown(run, project_cfg)
        report_dir = REPORTS_ROOT / project_id
        report_dir.mkdir(parents=True, exist_ok=True)
        report_path = report_dir / f"{run_id}.md"
        report_path.write_text(markdown, encoding="utf-8")
        return str(report_path)
    except Exception:
        logger.warning(
            "Run report generation failed for project=%s run=%s", project_id, run_id,
            exc_info=True,
        )
        return None
