"""Per-run Markdown summary report — written for a business stakeholder,
not a developer.

Reuses existing pipeline output rather than recomputing anything:

- Header / status / source(s)         -> the ``run`` dict (project_shared's
  in-memory run record), already fully populated by the time
  ``_perform_project_run`` reaches its ``finally`` block.
- What was found / what converted     -> the persisted SML snapshot blob
  (``ModelRepository.get_snapshot(sml_snapshot_id).sml_blob``), the same
  blob ``snapshot_service.get_snapshot_report_compat`` already parses for
  the existing snapshot-report endpoint.
- What was dropped, and why           -> ``RunSummary.dropped_entities``
  (``DropRecord`` list), already reconciled by
  ``core/engine/finalize.py::_reconcile_dropped_entities`` and copied onto
  the run dict by the time this module runs.
- AI-assisted risk/confidence         -> ``SMLMetric.complexity_tier`` == 5,
  ``llm_self_reported_confidence``, ``validation_notes`` and the same
  risky-DAX-pattern check ``project_mapping_engine._compute_static_risk_tier``
  already uses for the dry-run page (imported, not reimplemented).

Every string here is written for someone who has never heard of a "drop
ledger" or a "translation tier" — no pipeline/internal terminology reaches
the rendered file. See ``_REASON_RULES``/``_STAGE_FALLBACKS`` for the
plain-language translation of every ``drop_ledger.record(...)`` reason in
the codebase as of writing (grep-verified against every call site).
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# Run reports get their own, run_id-scoped directory -- unlike the existing
# `output/<target>/<project_id>/...` convention (engine.py's
# _model_output_dir), which is project-keyed and gets overwritten by every
# new run. A report must survive being generated by a run that a later run
# then supersedes.
REPORTS_ROOT = Path("output") / "reports"


# ---------------------------------------------------------------------------
# Drop-reason -> plain-language translation
# ---------------------------------------------------------------------------
# (substring to match against the lowercased raw reason, plain-English
# sentence). Checked in order, first match wins. This list was built by
# grepping every drop_ledger.record(...)/DropRecord(...) call site in the
# codebase (dimensions_clause_builder.py, metrics_clause_builder.py,
# relationships_clause_builder.py, snowflake_emitter.py, tmsl_to_osi.py,
# tmsl_to_sml.py, run_service.py's post-deploy reconciliation) -- every
# reason string that exists today matches one of these rules. Anything that
# doesn't match (a future call site, or wording drift) falls through to
# _STAGE_FALLBACKS below, so the report never leaks a raw internal reason.
_REASON_RULES: List[Tuple[str, str]] = [
    (
        "auto-generated power bi",
        "An automatic calendar table Power BI creates behind the scenes. "
        "It isn't part of your real business data.",
    ),
    (
        "calculation group",
        "An advanced Power BI authoring feature not yet supported by this "
        "conversion. It doesn't represent a business metric on its own.",
    ),
    (
        "duplicate physical-column",
        "A duplicate copy of this field (differing only in upper/lower "
        "case) was found in the source. One copy was kept automatically.",
    ),
    (
        "null-cast placeholder",
        "This calculation's formula could not be converted, and there was "
        "no original definition left to try again with.",
    ),
    (
        "deterministic, rule-based, and llm translation tiers were all",
        "This calculation's formula was too complex or unusual for either "
        "our standard conversion rules or AI assistance to handle.",
    ),
    (
        "ambiguous in dataset",
        "This field's name matches more than one column in the underlying "
        "data, and we can't safely tell which one was intended.",
    ),
    (
        "not found in the live snowflake schema",
        "This field no longer exists in the connected database, so "
        "anything depending on it couldn't be included.",
    ),
    (
        "no live snowflake schema was fetched",
        "We couldn't confirm this field still exists in the database at "
        "the time of this run, so it was left out to be safe.",
    ),
    (
        "no live schema was",
        "A date field this calculation depends on couldn't be checked "
        "against the connected database, so it was left out to avoid a "
        "possibly-wrong result.",
    ),
    (
        "no tables alias",
        "This calculation depends on data that isn't available in this "
        "semantic model.",
    ),
    (
        "non-scalar construct",
        "This calculation's formula needs a type of data lookup the "
        "destination system can't run directly.",
    ),
    (
        "contains a subquery",
        "This calculation's formula needs a nested lookup the destination "
        "system can't run directly.",
    ),
    (
        "type mismatch",
        "This calculation combines two incompatible kinds of data (for "
        "example, a date and a plain number). It needs to be corrected "
        "before it can be included.",
    ),
    (
        "virtual power bi measures table",
        "This calculation lives in a Power BI area with no data columns "
        "of its own, and it couldn't be linked back to the real data "
        "table it depends on.",
    ),
    (
        "could not resolve all virtual measures-table",
        "This calculation refers to a data field that couldn't be matched "
        "to anything in the source model.",
    ),
    (
        "could not be resolved after normalization",
        "This calculation refers to a data field that couldn't be matched "
        "to anything in the source model.",
    ),
    (
        "no source_column+aggregation",
        "This calculation has no underlying formula or data field "
        "defined, so there was nothing to convert.",
    ),
    (
        "by-design excluded",
        "Excluded intentionally — this item isn't meant to produce a "
        "reportable value on its own.",
    ),
    (
        "unresolvable dataset aliases",
        "A connection between two tables that this depends on couldn't "
        "be matched to real columns in the source data.",
    ),
    (
        "resolved to empty after physical column resolution",
        "A connection between two tables that this depends on couldn't "
        "be matched to real columns in the source data.",
    ),
    (
        "deployment aborted mid-ddl-execution",
        "The deployment was interrupted partway through, after some "
        "changes had already been applied to the destination. We "
        "recommend verifying the destination before re-running.",
    ),
    (
        "rejected this identifier",
        "The destination database rejected this item's name, and it "
        "couldn't be automatically corrected.",
    ),
    (
        "absent from both the deployed semantic",
        "This calculation looked ready to deploy but couldn't be "
        "confirmed as live afterward — possibly lost silently during "
        "deployment. We recommend re-running or checking manually.",
    ),
]

# Per-stage safety net for any reason that doesn't match a rule above, keyed
# on the same DropStage string values RunSummary.dropped_entities carries
# (plus "reconciliation", the one ad-hoc stage run_service.py adds itself).
_STAGE_FALLBACKS: Dict[str, str] = {
    "extraction": "Excluded while reading the source file.",
    "dax_translation": "This calculation's formula could not be converted into a working query.",
    "schema_validation": "This calculation depends on data that isn't available yet.",
    "ddl_emission": "This item couldn't be built in the format the destination requires.",
    "ddl_deployment": "The destination database rejected this item during deployment.",
    "reconciliation": "This item couldn't be confirmed as successfully deployed.",
}

# Plain-language group headings for the same stages -- used instead of the
# raw stage name so the report never shows "DropStage" jargon while still
# preserving the useful "roughly when did this happen" grouping.
_STAGE_GROUP_LABELS: Dict[str, str] = {
    "extraction": "While reading your source file",
    "dax_translation": "While converting calculations",
    "schema_validation": "While checking against your database",
    "ddl_emission": "While preparing calculations for deployment",
    "ddl_deployment": "While deploying to {target}",
    "reconciliation": "After deployment, during verification",
}
_STAGE_ORDER = [
    "extraction",
    "dax_translation",
    "schema_validation",
    "ddl_emission",
    "ddl_deployment",
    "reconciliation",
]

# advisory_categories is a stable code, not free text -- REAL_DEPLOY_ONLY_
# ADVISORY_CATEGORIES in project_mapping_engine.py is a one-entry set today
# (ADVISORY_CATEGORY_UNREACHABLE_DIMENSION), so this dict has one real entry
# plus a generic fallback for whatever category is added next.
_ADVISORY_FALLBACK_MESSAGE = (
    "This calculation was flagged with a structural note during "
    "conversion. We recommend double-checking this number."
)


def _advisory_category_messages() -> Dict[str, str]:
    from semabridge.converter.dax_ast_parser import ADVISORY_CATEGORY_UNREACHABLE_DIMENSION

    return {
        ADVISORY_CATEGORY_UNREACHABLE_DIMENSION: (
            "This calculation references data from a different part of "
            "your source model that isn't connected to it. It converted, "
            "but we recommend double-checking this number."
        ),
    }


def humanize_drop_reason(record: Dict[str, Any]) -> str:
    """Translate one DropRecord dict's `reason` into a plain sentence."""
    reason = str(record.get("reason") or "")
    stage = str(record.get("stage") or "")
    lowered = reason.lower()
    for needle, plain in _REASON_RULES:
        if needle in lowered:
            return plain
    return _STAGE_FALLBACKS.get(
        stage, "This item could not be included in the converted model."
    )


def stage_group_label(stage: str, target_label: str = "the destination") -> str:
    template = _STAGE_GROUP_LABELS.get(stage, "During conversion")
    return template.format(target=target_label) if "{target}" in template else template


# ---------------------------------------------------------------------------
# SML snapshot loading / metric classification
# ---------------------------------------------------------------------------

def _load_snapshot_data(sml_snapshot_id: Optional[str]) -> Optional[Dict[str, Any]]:
    """Load a persisted SML snapshot's datasets/metrics/relationships.

    One extra DB read, exactly the pattern
    snapshot_service.get_snapshot_report_compat already uses to recompute
    total_models/total_columns for the existing snapshot-report endpoint --
    the live SMLModel object itself is discarded once ExecutionEngine.execute()
    returns, so this is the only place per-metric complexity_tier/
    llm_self_reported_confidence/advisory data still exists after the run.
    """
    if not sml_snapshot_id:
        return None
    try:
        from semabridge.repository.model_repository import ModelRepository

        snap = ModelRepository().get_snapshot(str(sml_snapshot_id))
    except Exception:
        logger.debug(
            "Run report: could not load snapshot %s", sml_snapshot_id, exc_info=True
        )
        return None
    if not snap or not isinstance(snap.sml_blob, dict):
        return None
    blob = snap.sml_blob
    datasets = [d for d in (blob.get("datasets") or []) if isinstance(d, dict)]
    return {
        "dataset_count": len(datasets),
        "column_count": sum(len(d.get("columns") or []) for d in datasets),
        "relationship_count": len(blob.get("relationships") or []),
        "metrics": [m for m in (blob.get("metrics") or []) if isinstance(m, dict)],
    }


def _classify_metrics(sml_metrics: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
    """Split a snapshot's metrics into Standard / Standard-with-a-flag /
    AI-assisted, reusing the same risky-DAX-pattern check the dry-run page's
    three-tier risk label already uses (project_mapping_engine.py) rather
    than reimplementing it.

    "known risky pattern" in _compute_static_risk_tier is structurally
    reachable ONLY inside its `if is_tier5:` branch -- so that signal is
    folded into the AI-assisted entries below, not a separate section.
    advisory_notes/advisory_categories (osi_to_sml.py's unreachable-
    dimension check), however, run over every metric regardless of tier --
    so a Standard-conversion metric can carry a real flag too, and does get
    one here.
    """
    from semabridge.api.services.project_mapping_engine import _has_known_risky_dax_pattern

    advisory_messages = _advisory_category_messages()
    standard: List[Dict[str, Any]] = []
    ai_assisted: List[Dict[str, Any]] = []

    for metric in sml_metrics:
        if not metric.get("sync_enabled", True):
            continue  # not successfully converted -- appears in the drop ledger instead
        name = metric.get("unique_name") or metric.get("label") or "Unnamed calculation"
        tier = metric.get("complexity_tier") or 1
        categories = metric.get("advisory_categories") or []
        notes_present = bool(metric.get("advisory_notes"))
        advisory_msgs = [advisory_messages.get(cat, _ADVISORY_FALLBACK_MESSAGE) for cat in categories]
        if not advisory_msgs and notes_present:
            advisory_msgs = [_ADVISORY_FALLBACK_MESSAGE]

        if tier == 5:
            is_risky = bool(metric.get("validation_notes")) or _has_known_risky_dax_pattern(
                str(metric.get("expression") or "")
            )
            ai_assisted.append(
                {
                    "name": name,
                    "confidence": metric.get("llm_self_reported_confidence"),
                    "risky": is_risky,
                    "advisory_msgs": advisory_msgs,
                }
            )
        else:
            standard.append({"name": name, "advisory_msgs": advisory_msgs})

    return {"standard": standard, "ai_assisted": ai_assisted}


# ---------------------------------------------------------------------------
# Source description (source-type-agnostic: local PBIX single/multi-file,
# Fabric)
# ---------------------------------------------------------------------------

def _parse_project_cfg(project_cfg: str) -> Dict[str, Any]:
    # Deliberately re-implemented here (not imported from run_service.py's
    # _compat_parse_project_cfg_dict) to avoid a circular import --
    # run_service.py imports write_run_report from this module.
    import yaml

    try:
        parsed = yaml.safe_load(project_cfg or "") or {}
        return parsed if isinstance(parsed, dict) else {}
    except Exception:
        return {}


def _describe_source(project_cfg: str, run: Dict[str, Any]) -> Tuple[str, List[str]]:
    """Returns (source kind label, [one description per source file/dataset]).

    Reads the same source config every source type already funnels through
    (execution_config.SourceConfig / sync_execution_service._build_sync_jobs)
    -- nothing here branches on anything other than `type`.
    """
    parsed = _parse_project_cfg(project_cfg)
    source_cfg = parsed.get("source") if isinstance(parsed.get("source"), dict) else {}
    source_type = str(run.get("source_type") or source_cfg.get("type") or "").lower()

    if source_type == "pbix":
        pbix_path = source_cfg.get("pbix_path") or source_cfg.get("source_path") or source_cfg.get("file_path")
        if pbix_path:
            return "Local file", [Path(str(pbix_path)).name]
        models = source_cfg.get("models") or []
        if models:
            return "Local files", [Path(str(m)).name for m in models]
        labels = [
            str(r.get("model")) for r in (run.get("results") or [])
            if isinstance(r, dict) and r.get("model")
        ]
        return "Local file(s)", labels or ["(file name unavailable)"]

    if source_type == "fabric":
        dataset = source_cfg.get("dataset_id") or "(unknown dataset)"
        workspace = source_cfg.get("workspace_id")
        label = f"Fabric dataset {dataset}"
        if workspace:
            label += f" (workspace {workspace})"
        return "Microsoft Fabric", [label]

    if source_type == "snowflake":
        models = source_cfg.get("models") or []
        return "Snowflake", [str(m) for m in models] or ["(view name unavailable)"]

    return source_type.title() or "Unknown source", []


def _describe_source_for_result(
    result: Dict[str, Any], project_cfg: str, run: Dict[str, Any]
) -> Tuple[str, List[str]]:
    """Same (source kind, [files]) shape as _describe_source(), but scoped to
    ONE model's own result -- used when rendering a per-model report for a
    multi-PBIX batch, so its "Source:" line names only that file instead of
    every file in the batch (see generate_per_model_reports()).

    Falls back to the whole-run description when the result carries no
    pbix_path of its own (single-model runs, and non-PBIX sources, which
    don't fan out into multiple files today).
    """
    pbix_path = result.get("pbix_path")
    if pbix_path:
        return "Local file", [Path(str(pbix_path)).name]
    return _describe_source(project_cfg, run)


# ---------------------------------------------------------------------------
# JSON summary data (accordion view) -- ported from demo_version_ref's
# _gather_run_report_data()/build_run_report_data(), adapted to this
# codebase's current _classify_metrics() (Standard/AI-assisted only --
# no third "Needs Review" tier yet, see the followup_needs_review_
# classification memory/follow-up item; needs_review is always []
# below rather than omitted, so the frontend's three-tier tab structure
# doesn't need a special case for its absence).
#
# Deliberately NOT unified with generate_run_report_markdown()'s own
# gathering loop below, even though the two compute near-identical data:
# that function is already relied on by write_run_report()/
# write_per_model_run_reports() (tested, in production use), and
# refactoring it to share this loop would risk regressing the Markdown
# path for a JSON-view feature. Small duplication accepted deliberately.
# ---------------------------------------------------------------------------


def _gather_run_report_data(run: Dict[str, Any]) -> Dict[str, Any]:
    """Single source of truth for one run's (or one model's, when `run` has
    already been scoped to a single result -- see generate_per_model_reports()'s
    scoping trick) report data, structured for build_run_report_data()'s
    JSON view.

    Returns {"crashed": True, "error": str} if the run never reached
    ExecutionEngine.execute() (no RunSummary at all to report on) -- OR, with
    "unavailable": True added, if the run actually completed but its
    results/summary blob simply isn't available in THIS process's memory
    right now. The two look identical from run.get("results") alone (both
    are just "no results"), but they are not the same situation: `results`,
    `summary`, `logs`, and `stage_states` are deliberately stripped before
    the compat store is persisted to disk (see project_shared.py's
    _RUN_BLOB_KEYS/_strip_run_blobs -- kept small/fast on purpose) and are
    never rebuilt by get_project_runs_compat()'s ORM-fallback branch either,
    so ANY run reconstructed after a server restart looks exactly like a
    pre-extraction crash to this function even when it succeeded. A run
    with a terminal, non-failure status could not have "crashed before
    reading the source file" -- that combination means the data is simply
    gone from this process, not that the run failed.
    """
    project_name = str(run.get("project_name") or run.get("project_id") or "Project")
    model_results = [r for r in (run.get("results") or []) if isinstance(r, dict)]
    if not model_results:
        top_summary = run.get("summary") if isinstance(run.get("summary"), dict) else {}
        if top_summary:
            model_results = [
                {
                    "model": project_name,
                    "summary": top_summary,
                    "dropped_entities": top_summary.get("dropped_entities") or [],
                }
            ]

    if not model_results:
        status = str(run.get("status") or "").lower()
        if status in ("success", "warning", "partial"):
            return {
                "crashed": True,
                "unavailable": True,
                "error": (
                    f"This run completed with status '{status}', but its detailed "
                    "report data is no longer available in this session (for "
                    "example, after a server restart). Try the Raw Report tab, or "
                    "Download Raw .md, if a saved report file still exists."
                ),
            }
        return {
            "crashed": True,
            "error": str(run.get("error") or run.get("message") or "Unknown error."),
        }

    multi_model = len(model_results) > 1
    dataset_count = column_count = metric_count = relationship_count = 0
    standard: List[Dict[str, Any]] = []
    ai_assisted: List[Dict[str, Any]] = []
    dropped_by_stage: Dict[str, List[Dict[str, Any]]] = {}
    excluded_by_design_by_stage: Dict[str, List[Dict[str, Any]]] = {}
    target_type = ""

    for result in model_results:
        model_label = str(result.get("model") or "")
        summary = result.get("summary") if isinstance(result.get("summary"), dict) else {}
        target_type = target_type or str(summary.get("target_type") or "")
        model_dropped = [
            d for d in (result.get("dropped_entities") or summary.get("dropped_entities") or [])
            if isinstance(d, dict)
        ]

        snap_data = _load_snapshot_data(summary.get("sml_snapshot_id"))
        if snap_data:
            extraction_table_drops = sum(
                1 for d in model_dropped
                if d.get("stage") == "extraction" and d.get("entity_kind") == "table"
            )
            schema_column_drops = sum(
                1 for d in model_dropped
                if d.get("stage") == "schema_validation" and d.get("entity_kind") == "column"
            )
            emission_relationship_drops = sum(
                1 for d in model_dropped
                if d.get("stage") == "ddl_emission" and d.get("entity_kind") == "relationship"
            )
            dataset_count += snap_data["dataset_count"] + extraction_table_drops
            column_count += snap_data["column_count"] + schema_column_drops
            relationship_count += snap_data["relationship_count"] + emission_relationship_drops
            metric_count += len(snap_data["metrics"])

            classified = _classify_metrics(snap_data["metrics"])
            prefix = f"{model_label}: " if multi_model and model_label else ""
            for entry in classified["standard"]:
                standard.append({**entry, "name": f"{prefix}{entry['name']}"})
            for entry in classified["ai_assisted"]:
                ai_assisted.append({**entry, "name": f"{prefix}{entry['name']}"})

        for record in model_dropped:
            stage = str(record.get("stage") or "unknown")
            target_group = excluded_by_design_by_stage if record.get("by_design") else dropped_by_stage
            target_group.setdefault(stage, []).append(record)

    return {
        "crashed": False,
        "target_type": target_type,
        "counts": {
            "datasets": dataset_count,
            "columns": column_count,
            "metrics": metric_count,
            "relationships": relationship_count,
        },
        "standard": standard,
        "ai_assisted": ai_assisted,
        "needs_review": [],
        "dropped_by_stage": dropped_by_stage,
        "excluded_by_design_by_stage": excluded_by_design_by_stage,
    }


def build_run_report_data(
    run: Dict[str, Any],
    project_cfg: str,
    source_override: Optional[Tuple[str, List[str]]] = None,
) -> Dict[str, Any]:
    """JSON-friendly counterpart to generate_run_report_markdown, for the
    frontend's accordion-style summary view (RunReportSummary.jsx):
    collapsed shows clean counts per category, expanded shows full
    per-item detail. `source_override` lets a caller scope this to one
    model's own result (see generate_per_model_reports()'s identical
    scoping trick for the Markdown path).
    """
    project_name = str(run.get("project_name") or run.get("project_id") or "Project")
    run_id = str(run.get("run_id") or run.get("id") or "unknown")
    status = str(run.get("status") or "failed").lower()
    status_label, _status_icon = _STATUS_LABELS.get(status, ("Unknown", "❓"))
    source_kind, source_files = source_override or _describe_source(project_cfg, run)

    header = {
        "run_id": run_id,
        "project_name": project_name,
        "status": status,
        "status_label": status_label,
        "source_kind": source_kind,
        "source_files": source_files,
        "started_at": run.get("started_at"),
        "completed_at": run.get("completed_at"),
        "duration_label": _format_duration(run.get("duration_ms")),
    }

    data = _gather_run_report_data(run)
    if data["crashed"]:
        return {**header, "crashed": True, "unavailable": data.get("unavailable", False), "error": data["error"]}

    counts = data["counts"]
    standard, ai_assisted, needs_review = data["standard"], data["ai_assisted"], data["needs_review"]
    dropped_by_stage, target_type = data["dropped_by_stage"], data["target_type"]
    excluded_by_design_by_stage = data["excluded_by_design_by_stage"]
    target_label = target_type.title() if target_type else "the destination"

    def _stage_sections(by_stage: Dict[str, List[Dict[str, Any]]]) -> List[Dict[str, Any]]:
        ordered_stages = _STAGE_ORDER + [s for s in by_stage if s not in _STAGE_ORDER]
        sections = []
        for stage in ordered_stages:
            records = by_stage.get(stage)
            if not records:
                continue
            sections.append({
                "stage": stage,
                "label": stage_group_label(stage, target_label),
                "items": [
                    {
                        "name": record.get("entity_name") or "(unnamed)",
                        "entity_kind": record.get("entity_kind"),
                        "reason": humanize_drop_reason(record),
                    }
                    for record in records
                ],
            })
        return sections

    dropped_count = sum(len(records) for records in dropped_by_stage.values())
    excluded_by_design_count = sum(len(records) for records in excluded_by_design_by_stage.values())

    return {
        **header,
        "crashed": False,
        "counts": {
            "tables": counts["datasets"],
            "columns": counts["columns"],
            "calculations": counts["metrics"],
            "relationships": counts["relationships"],
            "converted_total": len(standard) + len(ai_assisted) + len(needs_review),
            "standard": len(standard),
            "ai_assisted": len(ai_assisted),
            "needs_review": len(needs_review),
            "dropped": dropped_count,
            "excluded_by_design": excluded_by_design_count,
        },
        "sections": {
            "standard": standard,
            "ai_assisted": ai_assisted,
            "needs_review": needs_review,
            "dropped": _stage_sections(dropped_by_stage),
            "excluded_by_design": _stage_sections(excluded_by_design_by_stage),
        },
    }


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

_STATUS_LABELS: Dict[str, Tuple[str, str]] = {
    "success": ("Completed successfully", "✅"),
    "warning": ("Completed — a few items need your attention", "⚠️"),
    "failed": ("Did not complete successfully", "❌"),
}


def _format_duration(duration_ms: Any) -> Optional[str]:
    try:
        total_seconds = int(float(duration_ms) / 1000)
    except (TypeError, ValueError):
        return None
    if total_seconds <= 0:
        return None
    minutes, seconds = divmod(total_seconds, 60)
    return f"{minutes}m {seconds}s" if minutes else f"{seconds}s"


def generate_run_report_markdown(
    run: Dict[str, Any],
    project_cfg: str,
    source_override: Optional[Tuple[str, List[str]]] = None,
) -> str:
    project_name = str(run.get("project_name") or run.get("project_id") or "Project")
    run_id = str(run.get("run_id") or run.get("id") or "unknown")
    status = str(run.get("status") or "failed").lower()
    status_label, status_icon = _STATUS_LABELS.get(status, ("Unknown", "❓"))
    source_kind, source_files = source_override or _describe_source(project_cfg, run)

    lines: List[str] = [
        f"# Run Report — {project_name}",
        "",
        f"**{status_icon} {status_label}**",
        "",
        f"- **Project:** {project_name}",
        f"- **Source:** {source_kind} — " + ", ".join(source_files or ["(unavailable)"]),
    ]
    started, completed = run.get("started_at"), run.get("completed_at")
    when = f"- **Started:** {started}" if started else ""
    if completed:
        when += f"  ·  **Completed:** {completed}"
    if when:
        lines.append(when)
    duration_label = _format_duration(run.get("duration_ms"))
    if duration_label:
        lines.append(f"- **Duration:** {duration_label}")
    lines.append(f"- **Run ID:** `{run_id}`")
    lines.append("")

    model_results = [r for r in (run.get("results") or []) if isinstance(r, dict)]
    if not model_results:
        top_summary = run.get("summary") if isinstance(run.get("summary"), dict) else {}
        if top_summary:
            model_results = [
                {
                    "model": project_name,
                    "summary": top_summary,
                    "dropped_entities": top_summary.get("dropped_entities") or [],
                }
            ]

    if not model_results:
        # Crashed before ExecutionEngine.execute() was even reached (bad
        # config, connection error, ...) -- there is no RunSummary at all,
        # so there is nothing to report on beyond the header and the error.
        lines.append("## What happened")
        lines.append("")
        lines.append("This run did not reach the point of reading your source file.")
        lines.append("")
        lines.append(f"**Error:** {run.get('error') or run.get('message') or 'Unknown error.'}")
        lines.append("")
        return "\n".join(lines)

    multi_model = len(model_results) > 1
    dataset_count = column_count = metric_count = relationship_count = 0
    standard: List[Dict[str, Any]] = []
    ai_assisted: List[Dict[str, Any]] = []
    dropped_by_stage: Dict[str, List[Dict[str, Any]]] = {}
    target_type = ""

    for result in model_results:
        model_label = str(result.get("model") or "")
        summary = result.get("summary") if isinstance(result.get("summary"), dict) else {}
        target_type = target_type or str(summary.get("target_type") or "")
        model_dropped = [
            d for d in (result.get("dropped_entities") or summary.get("dropped_entities") or [])
            if isinstance(d, dict)
        ]

        snap_data = _load_snapshot_data(summary.get("sml_snapshot_id"))
        if snap_data:
            # "Found in source" adds back by-design/schema-validation drops
            # so this reflects what was actually in the source file, not
            # just what survived into the final converted model.
            extraction_table_drops = sum(
                1 for d in model_dropped
                if d.get("stage") == "extraction" and d.get("entity_kind") == "table"
            )
            schema_column_drops = sum(
                1 for d in model_dropped
                if d.get("stage") == "schema_validation" and d.get("entity_kind") == "column"
            )
            emission_relationship_drops = sum(
                1 for d in model_dropped
                if d.get("stage") == "ddl_emission" and d.get("entity_kind") == "relationship"
            )
            dataset_count += snap_data["dataset_count"] + extraction_table_drops
            column_count += snap_data["column_count"] + schema_column_drops
            relationship_count += snap_data["relationship_count"] + emission_relationship_drops
            metric_count += len(snap_data["metrics"])

            classified = _classify_metrics(snap_data["metrics"])
            prefix = f"{model_label}: " if multi_model and model_label else ""
            for entry in classified["standard"]:
                standard.append({**entry, "name": f"{prefix}{entry['name']}"})
            for entry in classified["ai_assisted"]:
                ai_assisted.append({**entry, "name": f"{prefix}{entry['name']}"})

        for record in model_dropped:
            stage = str(record.get("stage") or "unknown")
            dropped_by_stage.setdefault(stage, []).append(record)

    # --- What we found in your source ------------------------------------
    lines.append("## What we found in your source")
    lines.append("")
    lines.append("| | Count |")
    lines.append("|---|---:|")
    lines.append(f"| Tables | {dataset_count} |")
    lines.append(f"| Columns | {column_count} |")
    lines.append(f"| Calculations | {metric_count} |")
    if relationship_count:
        lines.append(f"| Relationships between tables | {relationship_count} |")
    lines.append("")

    # --- What converted successfully --------------------------------------
    total_converted = len(standard) + len(ai_assisted)
    lines.append("## What converted successfully")
    lines.append("")
    lines.append(f"**{total_converted} of {metric_count} calculations converted.**")
    lines.append("")
    if standard:
        lines.append(f"### Standard conversion ({len(standard)})")
        lines.append("")
        lines.append("Converted automatically using SemaBridge's built-in conversion rules. No AI involved.")
        lines.append("")
        for entry in standard:
            if entry["advisory_msgs"]:
                lines.append(f"- **{entry['name']}** — _{entry['advisory_msgs'][0]}_")
            else:
                lines.append(f"- {entry['name']}")
        lines.append("")
    if ai_assisted:
        lines.append(f"### AI-assisted conversion ({len(ai_assisted)})")
        lines.append("")
        lines.append(
            "These calculations were too complex for our standard rules, so they "
            "were interpreted by AI instead. **We recommend verifying these numbers.**"
        )
        lines.append("")
        for entry in ai_assisted:
            sentence = (
                "This calculation was interpreted by AI rather than converted "
                "using a fixed rule — we recommend verifying this number."
            )
            confidence = entry.get("confidence")
            if isinstance(confidence, (int, float)):
                sentence += (
                    f" AI's own confidence in this calculation: "
                    f"{round(confidence * 100)}% (self-reported, not independently verified)."
                )
            if entry.get("risky"):
                sentence += " This calculation also matches a pattern that has caused problems before — please review it closely."
            for msg in entry.get("advisory_msgs") or []:
                sentence += f" {msg}"
            lines.append(f"- **{entry['name']}** — {sentence}")
        lines.append("")
    if not standard and not ai_assisted:
        lines.append("_Nothing converted successfully in this run._")
        lines.append("")

    # --- What we couldn't include, and why --------------------------------
    lines.append("## What we couldn't include, and why")
    lines.append("")
    if not dropped_by_stage:
        lines.append("Everything found in your source file was successfully converted and deployed.")
        lines.append("")
    else:
        target_label = target_type.title() if target_type else "the destination"
        ordered_stages = _STAGE_ORDER + [s for s in dropped_by_stage if s not in _STAGE_ORDER]
        for stage in ordered_stages:
            records = dropped_by_stage.get(stage)
            if not records:
                continue
            lines.append(f"### {stage_group_label(stage, target_label)} ({len(records)})")
            lines.append("")
            for record in records:
                name = record.get("entity_name") or "(unnamed)"
                plain = humanize_drop_reason(record)
                suffix = "  _(expected — not an error)_" if record.get("by_design") else ""
                lines.append(f"- **{name}** — {plain}{suffix}")
            lines.append("")

    return "\n".join(lines)


def write_run_report(run: Dict[str, Any], project_cfg: str) -> Optional[str]:
    """Render and persist the report for one run.

    Called unconditionally (success, partial, or failed) from
    _perform_project_run's `finally` block, so a failed run still produces
    a downloadable file. Never raises -- a reporting failure must not
    affect the run's own recorded outcome.
    """
    project_id = str(run.get("project_id") or "")
    run_id = str(run.get("run_id") or run.get("id") or "")
    if not project_id or not run_id:
        return None
    try:
        markdown = generate_run_report_markdown(run, project_cfg)
        report_dir = REPORTS_ROOT / project_id
        report_dir.mkdir(parents=True, exist_ok=True)
        report_path = report_dir / f"{run_id}.md"
        report_path.write_text(markdown, encoding="utf-8")
        return str(report_path)
    except Exception:
        logger.warning(
            "Run report generation failed for project=%s run=%s", project_id, run_id,
            exc_info=True,
        )
        return None


def _sanitize_report_filename_part(label: str, fallback: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_-]+", "_", str(label or "")).strip("_")
    return safe or fallback


def generate_per_model_reports(run: Dict[str, Any], project_cfg: str) -> List[Dict[str, str]]:
    """One full Markdown report PER model in a multi-PBIX batch, instead of
    the single combined report generate_run_report_markdown() produces when
    given the whole run.

    Reuses generate_run_report_markdown() completely unchanged -- each call
    just gets a `run` dict narrowed to that one model's own result (so none
    of the multi-model name-prefixing logic even triggers) and a
    source description narrowed to that model's own file (see
    _describe_source_for_result).

    Returns [] for a single-model (or resultless) run -- callers should fall
    back to the existing combined report in that case, since a "per-model"
    report is meaningless/redundant when there's only one model.
    """
    model_results = [r for r in (run.get("results") or []) if isinstance(r, dict)]
    if len(model_results) <= 1:
        return []

    reports: List[Dict[str, str]] = []
    for result in model_results:
        model_label = str(result.get("model") or "model")
        scoped_run = dict(run)
        scoped_run["results"] = [result]
        source_override = _describe_source_for_result(result, project_cfg, run)
        markdown = generate_run_report_markdown(scoped_run, project_cfg, source_override=source_override)
        reports.append({"model": model_label, "markdown": markdown})
    return reports


def _manifest_path(project_id: str, run_id: str) -> Path:
    return REPORTS_ROOT / project_id / f"{run_id}__manifest.json"


def write_per_model_run_reports(run: Dict[str, Any], project_cfg: str) -> List[Dict[str, str]]:
    """Render and persist one report file PER model for a multi-PBIX batch
    run, alongside (not instead of) the existing combined report written by
    write_run_report().

    Also writes a small JSON manifest (run_id__manifest.json) recording
    {model, path} for each file -- this is NOT persisted anywhere in the ORM
    (the `runs` table has no report columns at all; report state has only
    ever lived in the in-memory compat-store run dict, evicted on restart).
    Without the manifest, a restart would silently make every per-model
    download button disappear from the UI even though the .md files are
    still sitting on disk -- see load_persisted_model_reports(), which
    reads this manifest back to repopulate run["model_reports"] for a run
    reconstructed from the ORM after the in-memory store is gone.

    Returns [] for a single-model run -- the existing combined report IS the
    per-model report in that case, so there is nothing extra to write.
    Never raises, matching write_run_report()'s own error-handling contract.
    """
    project_id = str(run.get("project_id") or "")
    run_id = str(run.get("run_id") or run.get("id") or "")
    if not project_id or not run_id:
        return []
    try:
        per_model = generate_per_model_reports(run, project_cfg)
        if not per_model:
            return []
        report_dir = REPORTS_ROOT / project_id
        report_dir.mkdir(parents=True, exist_ok=True)
        written: List[Dict[str, str]] = []
        for idx, entry in enumerate(per_model, start=1):
            safe_label = _sanitize_report_filename_part(entry["model"], f"model{idx}")
            report_path = report_dir / f"{run_id}__{safe_label}.md"
            report_path.write_text(entry["markdown"], encoding="utf-8")
            written.append({"model": entry["model"], "path": str(report_path)})

        import json

        _manifest_path(project_id, run_id).write_text(json.dumps(written), encoding="utf-8")
        return written
    except Exception:
        logger.warning(
            "Per-model run report generation failed for project=%s run=%s", project_id, run_id,
            exc_info=True,
        )
        return []


def load_persisted_model_reports(project_id: str, run_id: str) -> List[Dict[str, str]]:
    """Disk-based reconstruction of write_per_model_run_reports()'s return
    value, for a run whose in-memory compat-store record is gone (server
    restart) -- read by get_project_runs_compat()'s ORM-fallback branch so
    per-model download buttons keep working after a restart instead of
    silently vanishing because run["model_reports"] was never repopulated.

    Reads the manifest instead of re-deriving {model, path} pairs from the
    on-disk filenames, because the filename only carries a lossily-sanitized
    version of the model label (_sanitize_report_filename_part) -- the
    manifest is the only place the exact original label survives, and the
    frontend needs that exact label to request the right file back via
    get_run_model_report_compat(). Never raises: a missing/corrupt manifest
    just means no per-model reports are offered, not a request failure --
    matching every other function in this module's error-handling contract.
    """
    import json

    manifest_path = _manifest_path(project_id, run_id)
    if not manifest_path.exists():
        return []
    try:
        entries = json.loads(manifest_path.read_text(encoding="utf-8"))
        if not isinstance(entries, list):
            return []
        return [
            {"model": str(e.get("model")), "path": str(e.get("path"))}
            for e in entries
            if isinstance(e, dict) and e.get("model") and e.get("path") and Path(str(e["path"])).exists()
        ]
    except Exception:
        logger.debug(
            "Could not load per-model report manifest for project=%s run=%s",
            project_id, run_id, exc_info=True,
        )
        return []
