project_name: ffdf
source:
  type: pbix
  pbix_path: C:/Users/Premasai/AppData/Local/Temp/semabridge/projects/proj-ffdf/ab788b2836cc481c9f3799dec4d864dd_continent.pbix
  pbix_file_path: C:/Users/Premasai/AppData/Local/Temp/semabridge/projects/proj-ffdf/ab788b2836cc481c9f3799dec4d864dd_continent.pbix
targets:
- type: snowflake
  identity_id: 241347f2-70b3-4bb5-9586-85bc50b2bd7b
ui:
  intermediate_format: osi
  editor_mode: form
options:
  auto_relationships: true
  generate_descriptions: true
project_id: proj-ffdf
display_name: ffdf
