"""initial_schema

Revision ID: ff10eddde5b9
Revises: 
Create Date: 2026-03-06 14:26:10.212887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff10eddde5b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_meta',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('cache_sync_history',
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('tables_processed', sa.Integer(), nullable=False),
    sa.Column('tables_changed', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('sync_id')
    )
    with op.batch_alter_table('cache_sync_history', schema=None) as batch_op:
        batch_op.create_index('ix_synchist_model_completed', ['model_name', 'completed_at'], unique=False)

    op.create_table('cache_table_hashes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('database', sa.String(length=255), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('column_hash', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('last_altered', sa.String(length=50), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('database', 'schema_name', 'table_name', name='uq_tablehash_database_schema_table')
    )
    op.create_table('command_log',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('command', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('adapter', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.String(length=255), nullable=True),
    sa.Column('initiated_by', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('command_log', schema=None) as batch_op:
        batch_op.create_index('ix_command_log_started', ['started_at'], unique=False)

    op.create_table('model_mappings',
    sa.Column('mapping_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_identifier', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_identifier', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_osi_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    op.create_table('model_version_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('version_tag', sa.String(length=100), nullable=False),
    sa.Column('yaml_hash', sa.String(length=64), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_version_history', schema=None) as batch_op:
        batch_op.create_index('ix_mvh_model_name', ['model_name'], unique=False)

    op.create_table('model_versions',
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.Column('version_tag', sa.String(length=100), nullable=True),
    sa.Column('is_rollback', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rollback_from_version', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('version_id')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index('ix_mv_model_workspace', ['model_id', 'workspace_id'], unique=False)

    op.create_table('projects',
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.String(length=255), nullable=True),
    sa.Column('adapter', sa.String(length=50), nullable=True),
    sa.Column('source_connection', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('schema_versions',
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('schema_hash', sa.String(length=64), nullable=False),
    sa.Column('schema_snapshot', sa.Text(), nullable=False),
    sa.Column('changes_from_previous', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_job_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('semabridge_credentials',
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('service', 'key')
    )
    op.create_table('sync_jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('conflict_resolution', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initiated_by', sa.String(length=20), nullable=True),
    sa.Column('source_folder', sa.Text(), nullable=True),
    sa.Column('source_connection', sa.Text(), nullable=True),
    sa.Column('target_workspace_id', sa.String(length=255), nullable=True),
    sa.Column('target_snowflake_schema', sa.String(length=255), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('completed_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('final_step', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('snapshots',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_tag', sa.String(length=100), nullable=True),
    sa.Column('sml_blob', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('initiated_by', sa.String(length=20), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshots_project_ts', ['project_id', 'timestamp'], unique=False)

    op.create_table('sync_checkpoints',
    sa.Column('checkpoint_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('last_processed_item_id', sa.String(length=36), nullable=False),
    sa.Column('last_processed_index', sa.Integer(), nullable=False),
    sa.Column('state_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['sync_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('checkpoint_id')
    )
    op.create_table('sync_conflicts',
    sa.Column('conflict_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_value', sa.Text(), nullable=True),
    sa.Column('target_value', sa.Text(), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['sync_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('conflict_id')
    )
    op.create_table('sync_job_items',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('osi_snapshot', sa.Text(), nullable=True),
    sa.Column('target_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['sync_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('user_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.create_index('ix_usercred_user_service', ['user_id', 'service'], unique=False)
        batch_op.create_index('ix_usercred_user_service_key', ['user_id', 'service', 'key'], unique=True)

    op.create_table('changes',
    sa.Column('change_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('object_name', sa.String(length=255), nullable=True),
    sa.Column('diff_type', sa.String(length=20), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.snapshot_id'], ),
    sa.PrimaryKeyConstraint('change_id')
    )
    op.create_table('source_artifacts',
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_artifacts')
    op.drop_table('changes')
    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.drop_index('ix_usercred_user_service_key')
        batch_op.drop_index('ix_usercred_user_service')

    op.drop_table('user_credentials')
    op.drop_table('sync_job_items')
    op.drop_table('sync_conflicts')
    op.drop_table('sync_checkpoints')
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshots_project_ts')

    op.drop_table('snapshots')
    op.drop_table('runs')
    op.drop_table('posts')
    op.drop_table('users')
    op.drop_table('sync_jobs')
    op.drop_table('semabridge_credentials')
    op.drop_table('schema_versions')
    op.drop_table('projects')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_mv_model_workspace')

    op.drop_table('model_versions')
    with op.batch_alter_table('model_version_history', schema=None) as batch_op:
        batch_op.drop_index('ix_mvh_model_name')

    op.drop_table('model_version_history')
    op.drop_table('model_mappings')
    with op.batch_alter_table('command_log', schema=None) as batch_op:
        batch_op.drop_index('ix_command_log_started')

    op.drop_table('command_log')
    op.drop_table('cache_table_hashes')
    with op.batch_alter_table('cache_sync_history', schema=None) as batch_op:
        batch_op.drop_index('ix_synchist_model_completed')

    op.drop_table('cache_sync_history')
    op.drop_table('cache_meta')
    # ### end Alembic commands ###
