"""
Semabridge Initialization Module.

Provides repository bootstrapping and global configuration generation.
Follows atomic initialization pattern with migration support for existing databases.
"""

from __future__ import annotations

import os
from datetime import datetime
from pathlib import Path
from typing import Optional, Dict, Any

import yaml
from copy import deepcopy
from pydantic import BaseModel

from semabridge.utils.logger import get_logger

logger = get_logger(__name__)


class InitResult(BaseModel):
    """Result of initialization operation."""
    success: bool
    repository_path: Path
    config_path: Optional[Path] = None
    message: str
    migrated: bool = False  # True if existing DB was migrated


# Default global configuration template for config.yaml
DEFAULT_CONFIG = {
    "core": {
        "intermediate_format": "OSI",
        "repository_path": "~/.semabridge/semabridge.db",
        "local_models_path": "~/.semabridge/models",
        "backup_retention": 5,
    },
    "database": {
        "backend": "orm",
        "connection_url_env": "SEMABRIDGE_DATABASE_URL",
    },
    "llm": {
        "enabled": False,
        "model": "gpt-4o-mini",
        "timeout_seconds": 30,
        "max_retries": 3,
        "api_key_env": "OPENAI_API_KEY",
    },
    "logging": {
        "level": "INFO",
        "format": "text",
        "dir": "~/.semabridge/logs",
        "redact_secrets": True,
    },
    "concurrency": {
        "max_concurrent_models": 4,
        "thread_pool_size": 8,
    },
    "options": {
        "global_exclude_models": [],
    },
    "config_path": "",  # auto-populated during init
}

GLOBAL_CONFIG_FILENAME = "config.yaml"
"""The global config is a separate entity from semabridge.yaml."""

CONFIG_YAML_HEADER = """# Semabridge Global Configuration (config.yaml)
# ============================================
# This file is SEPARATE from the project-level semabridge.yaml.
# It stores system-wide settings for logging, LLM, concurrency, etc.
#
# Generated by : semabridge init
# Generated at : {timestamp}
# Documentation: https://docs.semabridge.io/config
#
# IMPORTANT: Do NOT store secrets here. Use environment variables.

"""


class SemabridgeInitializer:
    """
    Initializes Semabridge repository and global configuration.
    
    Supports:
    - Local mode (--local): Creates repository in current working directory
    - Global mode: Creates repository in ~/.semabridge/
    - Migration: Updates existing databases to new schema without deletion
    """
    
    def __init__(
        self,
        repository_path: Optional[Path] = None,
        config_path: Optional[Path] = None,
        local: bool = False,
        log_dir: Optional[str] = None,
        db_backend: str = "orm",
        orm_connection_url_env: str = "SEMABRIDGE_DATABASE_URL",
    ):
        """
        Initialize with target repository path.

        Args:
            repository_path: Custom path for repository. If None, uses default.
            local: If True, use current working directory for repository.
            db_backend: Accepted for backward compatibility; always treated as
                ``"orm"`` — the database dialect is determined solely by
                ``SEMABRIDGE_DATABASE_URL``.
            orm_connection_url_env: Name of the environment variable that holds
                the database URL.
        """
        self.local = local
        # Accept legacy "duckdb" value silently; all backends now go through
        # SQLAlchemy so the distinction is irrelevant.
        self.db_backend = "orm"
        self.orm_connection_url_env = orm_connection_url_env
        
        if local:
            self.repository_path = Path.cwd() / "semabridge.db"
            self.config_dir = Path.cwd()
            self.default_log_dir = u"./logs"
        elif repository_path:
            raw_path = Path(repository_path).expanduser().resolve()
            if raw_path.is_dir():
                # If a directory is provided, append default filename
                self.repository_path = raw_path / "semabridge.db"
                logger.info(f"Directory provided for repository; using: {self.repository_path}")
            else:
                self.repository_path = raw_path
            self.config_dir = self.repository_path.parent
            self.default_log_dir = u"~/.semabridge/logs"
        else:
            # Default: ~/.semabridge/
            self.config_dir = Path.home() / ".semabridge"
            self.repository_path = self.config_dir / "semabridge.db"
            self.default_log_dir = u"~/.semabridge/logs"
        
        self.config_path = config_path or (self.config_dir / GLOBAL_CONFIG_FILENAME)
        self.log_dir = log_dir
    
    def initialize(self) -> InitResult:
        """
        Perform atomic initialization.
        
        1. Create directory structure if needed
        2. Create or migrate DuckDB repository
        3. Generate global config.yaml
        
        Returns:
            InitResult with paths and status
        """
        try:
            # Step 1: Create directory
            self._ensure_directory()
            
            # Step 2: Create or migrate repository via ORM
            migrated = self._create_or_migrate_repository()
            
            # Step 3: Generate config (only if not exists)
            config_created = self._generate_config()

            # Step 4: Bootstrap ORM tables when backend is orm
            if self.db_backend == "orm":
                self._bootstrap_orm_tables()

            # Invalidate cached DB config so subsequent calls pick up
            # the freshly-written config.yaml.
            try:
                from semabridge.core.db_resolver import clear_db_config_cache
                from semabridge.repository.orm.session_factory import reset_engine
                clear_db_config_cache()
                reset_engine()
            except Exception as exc:  # noqa: BLE001
                logger.debug("Could not reset DB engine after init: %s", exc)
            
            message = "Semabridge initialized successfully."
            if migrated:
                message = "Semabridge repository migrated to latest schema."
            elif not config_created:
                message = "Semabridge already initialized. Config unchanged."
            
            return InitResult(
                success=True,
                repository_path=self.repository_path,
                config_path=self.config_path if config_created else None,
                message=message,
                migrated=migrated,
            )
            
        except PermissionError as e:
            logger.error(f"Permission denied: {e}")
            return InitResult(
                success=False,
                repository_path=self.repository_path,
                message=f"Permission denied: Cannot write to {self.config_dir}. "
                        f"Check directory permissions or use --path to specify a different location.",
            )
        except Exception as e:
            logger.error(f"Initialization failed: {e}")
            return InitResult(
                success=False,
                repository_path=self.repository_path,
                message=f"Initialization failed: {str(e)}",
            )
    
    def _ensure_directory(self) -> None:
        """Create repository directory if it doesn't exist."""
        self.config_dir.mkdir(parents=True, exist_ok=True)
        logger.debug(f"Ensured directory exists: {self.config_dir}")
        
        # Create local models directory
        models_dir = self.config_dir / "models"
        models_dir.mkdir(parents=True, exist_ok=True)
        
        # Create a README in the models dir if it's empty
        readme = models_dir / "README.md"
        if not readme.exists():
            readme.write_text(
                "# SemaBridge Local Models\n\n"
                "Place your `.yaml` or `.json` semantic model definition files here.\n"
                "They will appear in the UI when you select **Local Repository** as the source type.\n\n"
                "## Directory Structure\n\n"
                "```\nmodels/\n  my_model.yaml\n  another_model.json\n```\n",
                encoding="utf-8",
            )
            logger.info(f"Created local models directory: {models_dir}")
    
    def _create_or_migrate_repository(self) -> bool:
        """Create or migrate the repository schema via SQLAlchemy ORM.

        ``Base.metadata.create_all()`` is idempotent — it issues
        ``CREATE TABLE IF NOT EXISTS`` for every mapped model, so this
        method is safe to call on both new and existing databases.

        Returns:
            ``True`` if an existing database was detected (migration path),
            ``False`` for a brand-new initialisation.
        """
        try:
            from sqlalchemy import inspect as sa_inspect
            from semabridge.repository.orm.base import Base
            from semabridge.repository.orm.session_factory import get_engine

            engine = get_engine()
            inspector = sa_inspect(engine)
            existing_tables = set(inspector.get_table_names())
            is_existing = bool(existing_tables)

            # Create all mapped tables that don't exist yet.
            Base.metadata.create_all(bind=engine)
            logger.info("Repository schema created/verified via SQLAlchemy ORM")

            if is_existing:
                logger.info(
                    "Existing database detected — schema delta applied by "
                    "create_all(); run Alembic for advanced column migrations."
                )

            return is_existing
        except Exception as exc:
            logger.warning(
                "ORM schema bootstrap failed (will retry after config write): %s", exc
            )
            return False
    
    def _generate_config(self) -> bool:
        """
        Generate global config.yaml with defaults.
        
        Returns:
            True if config was created, False if already exists
        """
        if self.config_path.exists():
            logger.debug(f"Config already exists: {self.config_path}")
            return False
        
        # Generate YAML content with header
        config = deepcopy(DEFAULT_CONFIG)
        config["core"]["repository_path"] = str(self.repository_path)
        
        # Set local_models_path relative to the repo location
        models_path = self.config_dir / "models"
        config["core"]["local_models_path"] = str(models_path)

        # Database backend configuration
        config["database"]["backend"] = "orm"
        config["database"]["connection_url_env"] = self.orm_connection_url_env
        # Remove legacy duckdb-only keys if present
        config["database"].pop("db_path", None)
        config["database"].pop("writer_thread_queue", None)

        # Self-referential: store the path of this config file in itself
        config["config_path"] = str(self.config_path)
        
        if self.log_dir:
             config["logging"]["dir"] = self.log_dir
        elif self.local:
             config["logging"]["dir"] = "./logs"
        
        yaml_content = CONFIG_YAML_HEADER.format(
            timestamp=datetime.now().isoformat()
        )
        yaml_content += yaml.dump(config, default_flow_style=False, sort_keys=False)
        
        self.config_path.write_text(yaml_content, encoding="utf-8")
        logger.info(f"Generated global config: {self.config_path}")
        logger.info(
            f"Note: config.yaml is stored alongside the DuckDB repository at "
            f"{self.config_dir}"
        )
        
        return True
    
    @staticmethod
    def get_default_repository_path() -> Path:
        """Get the default repository path."""
        return Path.home() / ".semabridge" / "semabridge.db"

    @staticmethod
    def get_default_config_path() -> Path:
        """Get the default global config path (config.yaml)."""
        return Path.home() / ".semabridge" / GLOBAL_CONFIG_FILENAME

    # ------------------------------------------------------------------
    # ORM bootstrap
    # ------------------------------------------------------------------

    def _bootstrap_orm_tables(self) -> None:
        """Create all ORM tables in the configured database.

        Thin wrapper kept for backward compatibility — the real work is
        done by :meth:`_create_or_migrate_repository`.  Called again
        after config.yaml is written so the engine can pick up the
        freshly-resolved URL.
        """
        try:
            from semabridge.repository.orm.base import Base
            from semabridge.repository.orm.session_factory import get_engine

            engine = get_engine()
            Base.metadata.create_all(bind=engine)
            logger.info("ORM tables bootstrapped successfully")
        except Exception as exc:
            logger.warning("Could not bootstrap ORM tables: %s", exc)
